// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `BenefitData.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:BenefitData)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct BenefitData {
    // message fields
    // @@protoc_insertion_point(field:BenefitData.status)
    pub status: u32,
    // @@protoc_insertion_point(field:BenefitData.level)
    pub level: u32,
    // @@protoc_insertion_point(field:BenefitData.config)
    pub config: ::protobuf::MessageField<super::OPGKKPEDKCL::OPGKKPEDKCL>,
    // @@protoc_insertion_point(field:BenefitData.JALHKMEOOPN)
    pub JALHKMEOOPN: u32,
    // special fields
    // @@protoc_insertion_point(special_field:BenefitData.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a BenefitData {
    fn default() -> &'a BenefitData {
        <BenefitData as ::protobuf::Message>::default_instance()
    }
}

impl BenefitData {
    pub fn new() -> BenefitData {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "status",
            |m: &BenefitData| { &m.status },
            |m: &mut BenefitData| { &mut m.status },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "level",
            |m: &BenefitData| { &m.level },
            |m: &mut BenefitData| { &mut m.level },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::OPGKKPEDKCL::OPGKKPEDKCL>(
            "config",
            |m: &BenefitData| { &m.config },
            |m: &mut BenefitData| { &mut m.config },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JALHKMEOOPN",
            |m: &BenefitData| { &m.JALHKMEOOPN },
            |m: &mut BenefitData| { &mut m.JALHKMEOOPN },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<BenefitData>(
            "BenefitData",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for BenefitData {
    const NAME: &'static str = "BenefitData";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                16 => {
                    self.status = is.read_uint32()?;
                },
                40 => {
                    self.level = is.read_uint32()?;
                },
                106 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.config)?;
                },
                112 => {
                    self.JALHKMEOOPN = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.status != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.status);
        }
        if self.level != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.level);
        }
        if let Some(v) = self.config.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.JALHKMEOOPN != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.JALHKMEOOPN);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.status != 0 {
            os.write_uint32(2, self.status)?;
        }
        if self.level != 0 {
            os.write_uint32(5, self.level)?;
        }
        if let Some(v) = self.config.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(13, v, os)?;
        }
        if self.JALHKMEOOPN != 0 {
            os.write_uint32(14, self.JALHKMEOOPN)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> BenefitData {
        BenefitData::new()
    }

    fn clear(&mut self) {
        self.status = 0;
        self.level = 0;
        self.config.clear();
        self.JALHKMEOOPN = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static BenefitData {
        static instance: BenefitData = BenefitData {
            status: 0,
            level: 0,
            config: ::protobuf::MessageField::none(),
            JALHKMEOOPN: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for BenefitData {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("BenefitData").unwrap()).clone()
    }
}

impl ::std::fmt::Display for BenefitData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BenefitData {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11BenefitData.proto\x1a\x11OPGKKPEDKCL.proto\"\x83\x01\n\x0bBenefitD\
    ata\x12\x16\n\x06status\x18\x02\x20\x01(\rR\x06status\x12\x14\n\x05level\
    \x18\x05\x20\x01(\rR\x05level\x12$\n\x06config\x18\r\x20\x01(\x0b2\x0c.O\
    PGKKPEDKCLR\x06config\x12\x20\n\x0bJALHKMEOOPN\x18\x0e\x20\x01(\rR\x0bJA\
    LHKMEOOPNb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::OPGKKPEDKCL::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(BenefitData::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
