// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `BPIPFFPFMDK.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:BPIPFFPFMDK)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct BPIPFFPFMDK {
    // message fields
    // @@protoc_insertion_point(field:BPIPFFPFMDK.ADOGOONNMOI)
    pub ADOGOONNMOI: u32,
    // @@protoc_insertion_point(field:BPIPFFPFMDK.pos)
    pub pos: u32,
    // @@protoc_insertion_point(field:BPIPFFPFMDK.count)
    pub count: u32,
    // @@protoc_insertion_point(field:BPIPFFPFMDK.ELPLMDAJPMD)
    pub ELPLMDAJPMD: u32,
    // special fields
    // @@protoc_insertion_point(special_field:BPIPFFPFMDK.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a BPIPFFPFMDK {
    fn default() -> &'a BPIPFFPFMDK {
        <BPIPFFPFMDK as ::protobuf::Message>::default_instance()
    }
}

impl BPIPFFPFMDK {
    pub fn new() -> BPIPFFPFMDK {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ADOGOONNMOI",
            |m: &BPIPFFPFMDK| { &m.ADOGOONNMOI },
            |m: &mut BPIPFFPFMDK| { &mut m.ADOGOONNMOI },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "pos",
            |m: &BPIPFFPFMDK| { &m.pos },
            |m: &mut BPIPFFPFMDK| { &mut m.pos },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "count",
            |m: &BPIPFFPFMDK| { &m.count },
            |m: &mut BPIPFFPFMDK| { &mut m.count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ELPLMDAJPMD",
            |m: &BPIPFFPFMDK| { &m.ELPLMDAJPMD },
            |m: &mut BPIPFFPFMDK| { &mut m.ELPLMDAJPMD },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<BPIPFFPFMDK>(
            "BPIPFFPFMDK",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for BPIPFFPFMDK {
    const NAME: &'static str = "BPIPFFPFMDK";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                32 => {
                    self.ADOGOONNMOI = is.read_uint32()?;
                },
                8 => {
                    self.pos = is.read_uint32()?;
                },
                80 => {
                    self.count = is.read_uint32()?;
                },
                104 => {
                    self.ELPLMDAJPMD = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.ADOGOONNMOI != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.ADOGOONNMOI);
        }
        if self.pos != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.pos);
        }
        if self.count != 0 {
            my_size += ::protobuf::rt::uint32_size(10, self.count);
        }
        if self.ELPLMDAJPMD != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.ELPLMDAJPMD);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.ADOGOONNMOI != 0 {
            os.write_uint32(4, self.ADOGOONNMOI)?;
        }
        if self.pos != 0 {
            os.write_uint32(1, self.pos)?;
        }
        if self.count != 0 {
            os.write_uint32(10, self.count)?;
        }
        if self.ELPLMDAJPMD != 0 {
            os.write_uint32(13, self.ELPLMDAJPMD)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> BPIPFFPFMDK {
        BPIPFFPFMDK::new()
    }

    fn clear(&mut self) {
        self.ADOGOONNMOI = 0;
        self.pos = 0;
        self.count = 0;
        self.ELPLMDAJPMD = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static BPIPFFPFMDK {
        static instance: BPIPFFPFMDK = BPIPFFPFMDK {
            ADOGOONNMOI: 0,
            pos: 0,
            count: 0,
            ELPLMDAJPMD: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for BPIPFFPFMDK {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("BPIPFFPFMDK").unwrap()).clone()
    }
}

impl ::std::fmt::Display for BPIPFFPFMDK {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BPIPFFPFMDK {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11BPIPFFPFMDK.proto\"y\n\x0bBPIPFFPFMDK\x12\x20\n\x0bADOGOONNMOI\x18\
    \x04\x20\x01(\rR\x0bADOGOONNMOI\x12\x10\n\x03pos\x18\x01\x20\x01(\rR\x03\
    pos\x12\x14\n\x05count\x18\n\x20\x01(\rR\x05count\x12\x20\n\x0bELPLMDAJP\
    MD\x18\r\x20\x01(\rR\x0bELPLMDAJPMDb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(BPIPFFPFMDK::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
