// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CmdChatType.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:CmdChatType)
pub enum CmdChatType {
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_MNFEPONEDDJ)
    CmdChatType_MNFEPONEDDJ = 0,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_PNIMKKIMPEO)
    CmdChatType_PNIMKKIMPEO = 3969,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_OELGMAPMEPA)
    CmdChatType_OELGMAPMEPA = 4000,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_ECGOGIPEBPI)
    CmdChatType_ECGOGIPEBPI = 3904,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_JOEDALCNLKP)
    CmdChatType_JOEDALCNLKP = 3962,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_LFPINHAMEGL)
    CmdChatType_LFPINHAMEGL = 3956,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_DDKGEFFKOCJ)
    CmdChatType_DDKGEFFKOCJ = 3981,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_KBJOEGLKLOL)
    CmdChatType_KBJOEGLKLOL = 3935,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_LPFLFCBPOFA)
    CmdChatType_LPFLFCBPOFA = 3919,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_NEMOGGGKFBC)
    CmdChatType_NEMOGGGKFBC = 3983,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_EGJLKBDLBNK)
    CmdChatType_EGJLKBDLBNK = 3923,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_BKDFPAHKAOL)
    CmdChatType_BKDFPAHKAOL = 3957,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_IKKPKGMOAIO)
    CmdChatType_IKKPKGMOAIO = 3940,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_EEMHELLKPBL)
    CmdChatType_EEMHELLKPBL = 3913,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_FJAJJOONNMB)
    CmdChatType_FJAJJOONNMB = 3984,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_IKOMANAPLIL)
    CmdChatType_IKOMANAPLIL = 3924,
    // @@protoc_insertion_point(enum_value:CmdChatType.CmdChatType_HNPCOLGKANE)
    CmdChatType_HNPCOLGKANE = 3946,
}

impl ::protobuf::Enum for CmdChatType {
    const NAME: &'static str = "CmdChatType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CmdChatType> {
        match value {
            0 => ::std::option::Option::Some(CmdChatType::CmdChatType_MNFEPONEDDJ),
            3969 => ::std::option::Option::Some(CmdChatType::CmdChatType_PNIMKKIMPEO),
            4000 => ::std::option::Option::Some(CmdChatType::CmdChatType_OELGMAPMEPA),
            3904 => ::std::option::Option::Some(CmdChatType::CmdChatType_ECGOGIPEBPI),
            3962 => ::std::option::Option::Some(CmdChatType::CmdChatType_JOEDALCNLKP),
            3956 => ::std::option::Option::Some(CmdChatType::CmdChatType_LFPINHAMEGL),
            3981 => ::std::option::Option::Some(CmdChatType::CmdChatType_DDKGEFFKOCJ),
            3935 => ::std::option::Option::Some(CmdChatType::CmdChatType_KBJOEGLKLOL),
            3919 => ::std::option::Option::Some(CmdChatType::CmdChatType_LPFLFCBPOFA),
            3983 => ::std::option::Option::Some(CmdChatType::CmdChatType_NEMOGGGKFBC),
            3923 => ::std::option::Option::Some(CmdChatType::CmdChatType_EGJLKBDLBNK),
            3957 => ::std::option::Option::Some(CmdChatType::CmdChatType_BKDFPAHKAOL),
            3940 => ::std::option::Option::Some(CmdChatType::CmdChatType_IKKPKGMOAIO),
            3913 => ::std::option::Option::Some(CmdChatType::CmdChatType_EEMHELLKPBL),
            3984 => ::std::option::Option::Some(CmdChatType::CmdChatType_FJAJJOONNMB),
            3924 => ::std::option::Option::Some(CmdChatType::CmdChatType_IKOMANAPLIL),
            3946 => ::std::option::Option::Some(CmdChatType::CmdChatType_HNPCOLGKANE),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CmdChatType> {
        match str {
            "CmdChatType_MNFEPONEDDJ" => ::std::option::Option::Some(CmdChatType::CmdChatType_MNFEPONEDDJ),
            "CmdChatType_PNIMKKIMPEO" => ::std::option::Option::Some(CmdChatType::CmdChatType_PNIMKKIMPEO),
            "CmdChatType_OELGMAPMEPA" => ::std::option::Option::Some(CmdChatType::CmdChatType_OELGMAPMEPA),
            "CmdChatType_ECGOGIPEBPI" => ::std::option::Option::Some(CmdChatType::CmdChatType_ECGOGIPEBPI),
            "CmdChatType_JOEDALCNLKP" => ::std::option::Option::Some(CmdChatType::CmdChatType_JOEDALCNLKP),
            "CmdChatType_LFPINHAMEGL" => ::std::option::Option::Some(CmdChatType::CmdChatType_LFPINHAMEGL),
            "CmdChatType_DDKGEFFKOCJ" => ::std::option::Option::Some(CmdChatType::CmdChatType_DDKGEFFKOCJ),
            "CmdChatType_KBJOEGLKLOL" => ::std::option::Option::Some(CmdChatType::CmdChatType_KBJOEGLKLOL),
            "CmdChatType_LPFLFCBPOFA" => ::std::option::Option::Some(CmdChatType::CmdChatType_LPFLFCBPOFA),
            "CmdChatType_NEMOGGGKFBC" => ::std::option::Option::Some(CmdChatType::CmdChatType_NEMOGGGKFBC),
            "CmdChatType_EGJLKBDLBNK" => ::std::option::Option::Some(CmdChatType::CmdChatType_EGJLKBDLBNK),
            "CmdChatType_BKDFPAHKAOL" => ::std::option::Option::Some(CmdChatType::CmdChatType_BKDFPAHKAOL),
            "CmdChatType_IKKPKGMOAIO" => ::std::option::Option::Some(CmdChatType::CmdChatType_IKKPKGMOAIO),
            "CmdChatType_EEMHELLKPBL" => ::std::option::Option::Some(CmdChatType::CmdChatType_EEMHELLKPBL),
            "CmdChatType_FJAJJOONNMB" => ::std::option::Option::Some(CmdChatType::CmdChatType_FJAJJOONNMB),
            "CmdChatType_IKOMANAPLIL" => ::std::option::Option::Some(CmdChatType::CmdChatType_IKOMANAPLIL),
            "CmdChatType_HNPCOLGKANE" => ::std::option::Option::Some(CmdChatType::CmdChatType_HNPCOLGKANE),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CmdChatType] = &[
        CmdChatType::CmdChatType_MNFEPONEDDJ,
        CmdChatType::CmdChatType_PNIMKKIMPEO,
        CmdChatType::CmdChatType_OELGMAPMEPA,
        CmdChatType::CmdChatType_ECGOGIPEBPI,
        CmdChatType::CmdChatType_JOEDALCNLKP,
        CmdChatType::CmdChatType_LFPINHAMEGL,
        CmdChatType::CmdChatType_DDKGEFFKOCJ,
        CmdChatType::CmdChatType_KBJOEGLKLOL,
        CmdChatType::CmdChatType_LPFLFCBPOFA,
        CmdChatType::CmdChatType_NEMOGGGKFBC,
        CmdChatType::CmdChatType_EGJLKBDLBNK,
        CmdChatType::CmdChatType_BKDFPAHKAOL,
        CmdChatType::CmdChatType_IKKPKGMOAIO,
        CmdChatType::CmdChatType_EEMHELLKPBL,
        CmdChatType::CmdChatType_FJAJJOONNMB,
        CmdChatType::CmdChatType_IKOMANAPLIL,
        CmdChatType::CmdChatType_HNPCOLGKANE,
    ];
}

impl ::protobuf::EnumFull for CmdChatType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("CmdChatType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            CmdChatType::CmdChatType_MNFEPONEDDJ => 0,
            CmdChatType::CmdChatType_PNIMKKIMPEO => 1,
            CmdChatType::CmdChatType_OELGMAPMEPA => 2,
            CmdChatType::CmdChatType_ECGOGIPEBPI => 3,
            CmdChatType::CmdChatType_JOEDALCNLKP => 4,
            CmdChatType::CmdChatType_LFPINHAMEGL => 5,
            CmdChatType::CmdChatType_DDKGEFFKOCJ => 6,
            CmdChatType::CmdChatType_KBJOEGLKLOL => 7,
            CmdChatType::CmdChatType_LPFLFCBPOFA => 8,
            CmdChatType::CmdChatType_NEMOGGGKFBC => 9,
            CmdChatType::CmdChatType_EGJLKBDLBNK => 10,
            CmdChatType::CmdChatType_BKDFPAHKAOL => 11,
            CmdChatType::CmdChatType_IKKPKGMOAIO => 12,
            CmdChatType::CmdChatType_EEMHELLKPBL => 13,
            CmdChatType::CmdChatType_FJAJJOONNMB => 14,
            CmdChatType::CmdChatType_IKOMANAPLIL => 15,
            CmdChatType::CmdChatType_HNPCOLGKANE => 16,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for CmdChatType {
    fn default() -> Self {
        CmdChatType::CmdChatType_MNFEPONEDDJ
    }
}

impl CmdChatType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<CmdChatType>("CmdChatType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11CmdChatType.proto*\x8a\x04\n\x0bCmdChatType\x12\x1b\n\x17CmdChatTy\
    pe_MNFEPONEDDJ\x10\0\x12\x1c\n\x17CmdChatType_PNIMKKIMPEO\x10\x81\x1f\
    \x12\x1c\n\x17CmdChatType_OELGMAPMEPA\x10\xa0\x1f\x12\x1c\n\x17CmdChatTy\
    pe_ECGOGIPEBPI\x10\xc0\x1e\x12\x1c\n\x17CmdChatType_JOEDALCNLKP\x10\xfa\
    \x1e\x12\x1c\n\x17CmdChatType_LFPINHAMEGL\x10\xf4\x1e\x12\x1c\n\x17CmdCh\
    atType_DDKGEFFKOCJ\x10\x8d\x1f\x12\x1c\n\x17CmdChatType_KBJOEGLKLOL\x10\
    \xdf\x1e\x12\x1c\n\x17CmdChatType_LPFLFCBPOFA\x10\xcf\x1e\x12\x1c\n\x17C\
    mdChatType_NEMOGGGKFBC\x10\x8f\x1f\x12\x1c\n\x17CmdChatType_EGJLKBDLBNK\
    \x10\xd3\x1e\x12\x1c\n\x17CmdChatType_BKDFPAHKAOL\x10\xf5\x1e\x12\x1c\n\
    \x17CmdChatType_IKKPKGMOAIO\x10\xe4\x1e\x12\x1c\n\x17CmdChatType_EEMHELL\
    KPBL\x10\xc9\x1e\x12\x1c\n\x17CmdChatType_FJAJJOONNMB\x10\x90\x1f\x12\
    \x1c\n\x17CmdChatType_IKOMANAPLIL\x10\xd4\x1e\x12\x1c\n\x17CmdChatType_H\
    NPCOLGKANE\x10\xea\x1eb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(CmdChatType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
