// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CmdExpeditionType.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:CmdExpeditionType)
pub enum CmdExpeditionType {
    // @@protoc_insertion_point(enum_value:CmdExpeditionType.OKPCOBCMOFF_NLCDGIPGFDJ)
    OKPCOBCMOFF_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:CmdExpeditionType.OKPCOBCMOFF_OLCHGINAEIG)
    OKPCOBCMOFF_OLCHGINAEIG = 2514,
    // @@protoc_insertion_point(enum_value:CmdExpeditionType.OKPCOBCMOFF_KDNHLKEOHHA)
    OKPCOBCMOFF_KDNHLKEOHHA = 2509,
    // @@protoc_insertion_point(enum_value:CmdExpeditionType.OKPCOBCMOFF_MKBNPFGGANC)
    OKPCOBCMOFF_MKBNPFGGANC = 2535,
    // @@protoc_insertion_point(enum_value:CmdExpeditionType.OKPCOBCMOFF_DFJDNLNFKLG)
    OKPCOBCMOFF_DFJDNLNFKLG = 2510,
    // @@protoc_insertion_point(enum_value:CmdExpeditionType.OKPCOBCMOFF_CHEPKADENJL)
    OKPCOBCMOFF_CHEPKADENJL = 2523,
    // @@protoc_insertion_point(enum_value:CmdExpeditionType.OKPCOBCMOFF_ECHFAEDEFLG)
    OKPCOBCMOFF_ECHFAEDEFLG = 2506,
    // @@protoc_insertion_point(enum_value:CmdExpeditionType.OKPCOBCMOFF_CCMNFGHDCDO)
    OKPCOBCMOFF_CCMNFGHDCDO = 2502,
}

impl ::protobuf::Enum for CmdExpeditionType {
    const NAME: &'static str = "CmdExpeditionType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CmdExpeditionType> {
        match value {
            0 => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_NLCDGIPGFDJ),
            2514 => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_OLCHGINAEIG),
            2509 => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_KDNHLKEOHHA),
            2535 => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_MKBNPFGGANC),
            2510 => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_DFJDNLNFKLG),
            2523 => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_CHEPKADENJL),
            2506 => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_ECHFAEDEFLG),
            2502 => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_CCMNFGHDCDO),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CmdExpeditionType> {
        match str {
            "OKPCOBCMOFF_NLCDGIPGFDJ" => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_NLCDGIPGFDJ),
            "OKPCOBCMOFF_OLCHGINAEIG" => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_OLCHGINAEIG),
            "OKPCOBCMOFF_KDNHLKEOHHA" => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_KDNHLKEOHHA),
            "OKPCOBCMOFF_MKBNPFGGANC" => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_MKBNPFGGANC),
            "OKPCOBCMOFF_DFJDNLNFKLG" => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_DFJDNLNFKLG),
            "OKPCOBCMOFF_CHEPKADENJL" => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_CHEPKADENJL),
            "OKPCOBCMOFF_ECHFAEDEFLG" => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_ECHFAEDEFLG),
            "OKPCOBCMOFF_CCMNFGHDCDO" => ::std::option::Option::Some(CmdExpeditionType::OKPCOBCMOFF_CCMNFGHDCDO),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CmdExpeditionType] = &[
        CmdExpeditionType::OKPCOBCMOFF_NLCDGIPGFDJ,
        CmdExpeditionType::OKPCOBCMOFF_OLCHGINAEIG,
        CmdExpeditionType::OKPCOBCMOFF_KDNHLKEOHHA,
        CmdExpeditionType::OKPCOBCMOFF_MKBNPFGGANC,
        CmdExpeditionType::OKPCOBCMOFF_DFJDNLNFKLG,
        CmdExpeditionType::OKPCOBCMOFF_CHEPKADENJL,
        CmdExpeditionType::OKPCOBCMOFF_ECHFAEDEFLG,
        CmdExpeditionType::OKPCOBCMOFF_CCMNFGHDCDO,
    ];
}

impl ::protobuf::EnumFull for CmdExpeditionType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("CmdExpeditionType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            CmdExpeditionType::OKPCOBCMOFF_NLCDGIPGFDJ => 0,
            CmdExpeditionType::OKPCOBCMOFF_OLCHGINAEIG => 1,
            CmdExpeditionType::OKPCOBCMOFF_KDNHLKEOHHA => 2,
            CmdExpeditionType::OKPCOBCMOFF_MKBNPFGGANC => 3,
            CmdExpeditionType::OKPCOBCMOFF_DFJDNLNFKLG => 4,
            CmdExpeditionType::OKPCOBCMOFF_CHEPKADENJL => 5,
            CmdExpeditionType::OKPCOBCMOFF_ECHFAEDEFLG => 6,
            CmdExpeditionType::OKPCOBCMOFF_CCMNFGHDCDO => 7,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for CmdExpeditionType {
    fn default() -> Self {
        CmdExpeditionType::OKPCOBCMOFF_NLCDGIPGFDJ
    }
}

impl CmdExpeditionType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<CmdExpeditionType>("CmdExpeditionType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x17CmdExpeditionType.proto*\x82\x02\n\x11CmdExpeditionType\x12\x1b\n\
    \x17OKPCOBCMOFF_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17OKPCOBCMOFF_OLCHGINAEIG\
    \x10\xd2\x13\x12\x1c\n\x17OKPCOBCMOFF_KDNHLKEOHHA\x10\xcd\x13\x12\x1c\n\
    \x17OKPCOBCMOFF_MKBNPFGGANC\x10\xe7\x13\x12\x1c\n\x17OKPCOBCMOFF_DFJDNLN\
    FKLG\x10\xce\x13\x12\x1c\n\x17OKPCOBCMOFF_CHEPKADENJL\x10\xdb\x13\x12\
    \x1c\n\x17OKPCOBCMOFF_ECHFAEDEFLG\x10\xca\x13\x12\x1c\n\x17OKPCOBCMOFF_C\
    CMNFGHDCDO\x10\xc6\x13b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(CmdExpeditionType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
