// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CmdEvolveBuildType.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:CmdEvolveBuildType)
pub enum CmdEvolveBuildType {
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_IINBLPOACOC)
    CmdEvolveBuildType_IINBLPOACOC = 0,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_KAPLENCCCBG)
    CmdEvolveBuildType_KAPLENCCCBG = 7128,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_MCEJEKEECCN)
    CmdEvolveBuildType_MCEJEKEECCN = 7101,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_HLPEAGKHMFL)
    CmdEvolveBuildType_HLPEAGKHMFL = 7112,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_PGGMADMLGEJ)
    CmdEvolveBuildType_PGGMADMLGEJ = 7124,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_JAGCJECMGML)
    CmdEvolveBuildType_JAGCJECMGML = 7107,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_PFAAKDMGMKC)
    CmdEvolveBuildType_PFAAKDMGMKC = 7119,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_MEACONLEBEG)
    CmdEvolveBuildType_MEACONLEBEG = 7140,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_NLKADELBGFK)
    CmdEvolveBuildType_NLKADELBGFK = 7134,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_OIJGLNHDFPP)
    CmdEvolveBuildType_OIJGLNHDFPP = 7130,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_LELOBDMGJDB)
    CmdEvolveBuildType_LELOBDMGJDB = 7109,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_IEBFEDOMNKM)
    CmdEvolveBuildType_IEBFEDOMNKM = 7114,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_EMICHDMFBOF)
    CmdEvolveBuildType_EMICHDMFBOF = 7108,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_IBPNCBPMFOE)
    CmdEvolveBuildType_IBPNCBPMFOE = 7141,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_LONNAFPGDHF)
    CmdEvolveBuildType_LONNAFPGDHF = 7129,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_OBKJGAKFHFO)
    CmdEvolveBuildType_OBKJGAKFHFO = 7138,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_CBEPCLLEBMG)
    CmdEvolveBuildType_CBEPCLLEBMG = 7104,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_DAELCLFMPEN)
    CmdEvolveBuildType_DAELCLFMPEN = 7146,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_GBPOGNFBNHP)
    CmdEvolveBuildType_GBPOGNFBNHP = 7102,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_JGCDHKNDKCN)
    CmdEvolveBuildType_JGCDHKNDKCN = 7123,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_EBHCKENHKON)
    CmdEvolveBuildType_EBHCKENHKON = 7103,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_DMALHBBDIBB)
    CmdEvolveBuildType_DMALHBBDIBB = 7139,
    // @@protoc_insertion_point(enum_value:CmdEvolveBuildType.CmdEvolveBuildType_BHHNBMBNJOK)
    CmdEvolveBuildType_BHHNBMBNJOK = 7118,
}

impl ::protobuf::Enum for CmdEvolveBuildType {
    const NAME: &'static str = "CmdEvolveBuildType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CmdEvolveBuildType> {
        match value {
            0 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_IINBLPOACOC),
            7128 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_KAPLENCCCBG),
            7101 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_MCEJEKEECCN),
            7112 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_HLPEAGKHMFL),
            7124 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_PGGMADMLGEJ),
            7107 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_JAGCJECMGML),
            7119 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_PFAAKDMGMKC),
            7140 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_MEACONLEBEG),
            7134 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_NLKADELBGFK),
            7130 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_OIJGLNHDFPP),
            7109 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_LELOBDMGJDB),
            7114 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_IEBFEDOMNKM),
            7108 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_EMICHDMFBOF),
            7141 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_IBPNCBPMFOE),
            7129 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_LONNAFPGDHF),
            7138 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_OBKJGAKFHFO),
            7104 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_CBEPCLLEBMG),
            7146 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_DAELCLFMPEN),
            7102 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_GBPOGNFBNHP),
            7123 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_JGCDHKNDKCN),
            7103 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_EBHCKENHKON),
            7139 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_DMALHBBDIBB),
            7118 => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_BHHNBMBNJOK),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CmdEvolveBuildType> {
        match str {
            "CmdEvolveBuildType_IINBLPOACOC" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_IINBLPOACOC),
            "CmdEvolveBuildType_KAPLENCCCBG" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_KAPLENCCCBG),
            "CmdEvolveBuildType_MCEJEKEECCN" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_MCEJEKEECCN),
            "CmdEvolveBuildType_HLPEAGKHMFL" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_HLPEAGKHMFL),
            "CmdEvolveBuildType_PGGMADMLGEJ" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_PGGMADMLGEJ),
            "CmdEvolveBuildType_JAGCJECMGML" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_JAGCJECMGML),
            "CmdEvolveBuildType_PFAAKDMGMKC" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_PFAAKDMGMKC),
            "CmdEvolveBuildType_MEACONLEBEG" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_MEACONLEBEG),
            "CmdEvolveBuildType_NLKADELBGFK" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_NLKADELBGFK),
            "CmdEvolveBuildType_OIJGLNHDFPP" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_OIJGLNHDFPP),
            "CmdEvolveBuildType_LELOBDMGJDB" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_LELOBDMGJDB),
            "CmdEvolveBuildType_IEBFEDOMNKM" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_IEBFEDOMNKM),
            "CmdEvolveBuildType_EMICHDMFBOF" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_EMICHDMFBOF),
            "CmdEvolveBuildType_IBPNCBPMFOE" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_IBPNCBPMFOE),
            "CmdEvolveBuildType_LONNAFPGDHF" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_LONNAFPGDHF),
            "CmdEvolveBuildType_OBKJGAKFHFO" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_OBKJGAKFHFO),
            "CmdEvolveBuildType_CBEPCLLEBMG" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_CBEPCLLEBMG),
            "CmdEvolveBuildType_DAELCLFMPEN" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_DAELCLFMPEN),
            "CmdEvolveBuildType_GBPOGNFBNHP" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_GBPOGNFBNHP),
            "CmdEvolveBuildType_JGCDHKNDKCN" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_JGCDHKNDKCN),
            "CmdEvolveBuildType_EBHCKENHKON" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_EBHCKENHKON),
            "CmdEvolveBuildType_DMALHBBDIBB" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_DMALHBBDIBB),
            "CmdEvolveBuildType_BHHNBMBNJOK" => ::std::option::Option::Some(CmdEvolveBuildType::CmdEvolveBuildType_BHHNBMBNJOK),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CmdEvolveBuildType] = &[
        CmdEvolveBuildType::CmdEvolveBuildType_IINBLPOACOC,
        CmdEvolveBuildType::CmdEvolveBuildType_KAPLENCCCBG,
        CmdEvolveBuildType::CmdEvolveBuildType_MCEJEKEECCN,
        CmdEvolveBuildType::CmdEvolveBuildType_HLPEAGKHMFL,
        CmdEvolveBuildType::CmdEvolveBuildType_PGGMADMLGEJ,
        CmdEvolveBuildType::CmdEvolveBuildType_JAGCJECMGML,
        CmdEvolveBuildType::CmdEvolveBuildType_PFAAKDMGMKC,
        CmdEvolveBuildType::CmdEvolveBuildType_MEACONLEBEG,
        CmdEvolveBuildType::CmdEvolveBuildType_NLKADELBGFK,
        CmdEvolveBuildType::CmdEvolveBuildType_OIJGLNHDFPP,
        CmdEvolveBuildType::CmdEvolveBuildType_LELOBDMGJDB,
        CmdEvolveBuildType::CmdEvolveBuildType_IEBFEDOMNKM,
        CmdEvolveBuildType::CmdEvolveBuildType_EMICHDMFBOF,
        CmdEvolveBuildType::CmdEvolveBuildType_IBPNCBPMFOE,
        CmdEvolveBuildType::CmdEvolveBuildType_LONNAFPGDHF,
        CmdEvolveBuildType::CmdEvolveBuildType_OBKJGAKFHFO,
        CmdEvolveBuildType::CmdEvolveBuildType_CBEPCLLEBMG,
        CmdEvolveBuildType::CmdEvolveBuildType_DAELCLFMPEN,
        CmdEvolveBuildType::CmdEvolveBuildType_GBPOGNFBNHP,
        CmdEvolveBuildType::CmdEvolveBuildType_JGCDHKNDKCN,
        CmdEvolveBuildType::CmdEvolveBuildType_EBHCKENHKON,
        CmdEvolveBuildType::CmdEvolveBuildType_DMALHBBDIBB,
        CmdEvolveBuildType::CmdEvolveBuildType_BHHNBMBNJOK,
    ];
}

impl ::protobuf::EnumFull for CmdEvolveBuildType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("CmdEvolveBuildType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            CmdEvolveBuildType::CmdEvolveBuildType_IINBLPOACOC => 0,
            CmdEvolveBuildType::CmdEvolveBuildType_KAPLENCCCBG => 1,
            CmdEvolveBuildType::CmdEvolveBuildType_MCEJEKEECCN => 2,
            CmdEvolveBuildType::CmdEvolveBuildType_HLPEAGKHMFL => 3,
            CmdEvolveBuildType::CmdEvolveBuildType_PGGMADMLGEJ => 4,
            CmdEvolveBuildType::CmdEvolveBuildType_JAGCJECMGML => 5,
            CmdEvolveBuildType::CmdEvolveBuildType_PFAAKDMGMKC => 6,
            CmdEvolveBuildType::CmdEvolveBuildType_MEACONLEBEG => 7,
            CmdEvolveBuildType::CmdEvolveBuildType_NLKADELBGFK => 8,
            CmdEvolveBuildType::CmdEvolveBuildType_OIJGLNHDFPP => 9,
            CmdEvolveBuildType::CmdEvolveBuildType_LELOBDMGJDB => 10,
            CmdEvolveBuildType::CmdEvolveBuildType_IEBFEDOMNKM => 11,
            CmdEvolveBuildType::CmdEvolveBuildType_EMICHDMFBOF => 12,
            CmdEvolveBuildType::CmdEvolveBuildType_IBPNCBPMFOE => 13,
            CmdEvolveBuildType::CmdEvolveBuildType_LONNAFPGDHF => 14,
            CmdEvolveBuildType::CmdEvolveBuildType_OBKJGAKFHFO => 15,
            CmdEvolveBuildType::CmdEvolveBuildType_CBEPCLLEBMG => 16,
            CmdEvolveBuildType::CmdEvolveBuildType_DAELCLFMPEN => 17,
            CmdEvolveBuildType::CmdEvolveBuildType_GBPOGNFBNHP => 18,
            CmdEvolveBuildType::CmdEvolveBuildType_JGCDHKNDKCN => 19,
            CmdEvolveBuildType::CmdEvolveBuildType_EBHCKENHKON => 20,
            CmdEvolveBuildType::CmdEvolveBuildType_DMALHBBDIBB => 21,
            CmdEvolveBuildType::CmdEvolveBuildType_BHHNBMBNJOK => 22,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for CmdEvolveBuildType {
    fn default() -> Self {
        CmdEvolveBuildType::CmdEvolveBuildType_IINBLPOACOC
    }
}

impl CmdEvolveBuildType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<CmdEvolveBuildType>("CmdEvolveBuildType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18CmdEvolveBuildType.proto*\xe6\x06\n\x12CmdEvolveBuildType\x12\"\n\
    \x1eCmdEvolveBuildType_IINBLPOACOC\x10\0\x12#\n\x1eCmdEvolveBuildType_KA\
    PLENCCCBG\x10\xd87\x12#\n\x1eCmdEvolveBuildType_MCEJEKEECCN\x10\xbd7\x12\
    #\n\x1eCmdEvolveBuildType_HLPEAGKHMFL\x10\xc87\x12#\n\x1eCmdEvolveBuildT\
    ype_PGGMADMLGEJ\x10\xd47\x12#\n\x1eCmdEvolveBuildType_JAGCJECMGML\x10\
    \xc37\x12#\n\x1eCmdEvolveBuildType_PFAAKDMGMKC\x10\xcf7\x12#\n\x1eCmdEvo\
    lveBuildType_MEACONLEBEG\x10\xe47\x12#\n\x1eCmdEvolveBuildType_NLKADELBG\
    FK\x10\xde7\x12#\n\x1eCmdEvolveBuildType_OIJGLNHDFPP\x10\xda7\x12#\n\x1e\
    CmdEvolveBuildType_LELOBDMGJDB\x10\xc57\x12#\n\x1eCmdEvolveBuildType_IEB\
    FEDOMNKM\x10\xca7\x12#\n\x1eCmdEvolveBuildType_EMICHDMFBOF\x10\xc47\x12#\
    \n\x1eCmdEvolveBuildType_IBPNCBPMFOE\x10\xe57\x12#\n\x1eCmdEvolveBuildTy\
    pe_LONNAFPGDHF\x10\xd97\x12#\n\x1eCmdEvolveBuildType_OBKJGAKFHFO\x10\xe2\
    7\x12#\n\x1eCmdEvolveBuildType_CBEPCLLEBMG\x10\xc07\x12#\n\x1eCmdEvolveB\
    uildType_DAELCLFMPEN\x10\xea7\x12#\n\x1eCmdEvolveBuildType_GBPOGNFBNHP\
    \x10\xbe7\x12#\n\x1eCmdEvolveBuildType_JGCDHKNDKCN\x10\xd37\x12#\n\x1eCm\
    dEvolveBuildType_EBHCKENHKON\x10\xbf7\x12#\n\x1eCmdEvolveBuildType_DMALH\
    BBDIBB\x10\xe37\x12#\n\x1eCmdEvolveBuildType_BHHNBMBNJOK\x10\xce7b\x06pr\
    oto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(CmdEvolveBuildType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
