// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CmdOfferingType.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:CmdOfferingType)
pub enum CmdOfferingType {
    // @@protoc_insertion_point(enum_value:CmdOfferingType.LIPONPBGOPN_NLCDGIPGFDJ)
    LIPONPBGOPN_NLCDGIPGFDJ = 0,
    // @@protoc_insertion_point(enum_value:CmdOfferingType.LIPONPBGOPN_FLPIHJLMCDM)
    LIPONPBGOPN_FLPIHJLMCDM = 6932,
    // @@protoc_insertion_point(enum_value:CmdOfferingType.LIPONPBGOPN_HGKELIFKFDP)
    LIPONPBGOPN_HGKELIFKFDP = 6928,
    // @@protoc_insertion_point(enum_value:CmdOfferingType.LIPONPBGOPN_FKLKKDCLGEN)
    LIPONPBGOPN_FKLKKDCLGEN = 6925,
    // @@protoc_insertion_point(enum_value:CmdOfferingType.LIPONPBGOPN_ANEEKCGOAMC)
    LIPONPBGOPN_ANEEKCGOAMC = 6923,
    // @@protoc_insertion_point(enum_value:CmdOfferingType.LIPONPBGOPN_ABEHDHJCDIL)
    LIPONPBGOPN_ABEHDHJCDIL = 6937,
    // @@protoc_insertion_point(enum_value:CmdOfferingType.LIPONPBGOPN_HMNDKFKCGNL)
    LIPONPBGOPN_HMNDKFKCGNL = 6938,
    // @@protoc_insertion_point(enum_value:CmdOfferingType.LIPONPBGOPN_FEFDACJCFIL)
    LIPONPBGOPN_FEFDACJCFIL = 6922,
}

impl ::protobuf::Enum for CmdOfferingType {
    const NAME: &'static str = "CmdOfferingType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CmdOfferingType> {
        match value {
            0 => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_NLCDGIPGFDJ),
            6932 => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_FLPIHJLMCDM),
            6928 => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_HGKELIFKFDP),
            6925 => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_FKLKKDCLGEN),
            6923 => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_ANEEKCGOAMC),
            6937 => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_ABEHDHJCDIL),
            6938 => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_HMNDKFKCGNL),
            6922 => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_FEFDACJCFIL),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CmdOfferingType> {
        match str {
            "LIPONPBGOPN_NLCDGIPGFDJ" => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_NLCDGIPGFDJ),
            "LIPONPBGOPN_FLPIHJLMCDM" => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_FLPIHJLMCDM),
            "LIPONPBGOPN_HGKELIFKFDP" => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_HGKELIFKFDP),
            "LIPONPBGOPN_FKLKKDCLGEN" => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_FKLKKDCLGEN),
            "LIPONPBGOPN_ANEEKCGOAMC" => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_ANEEKCGOAMC),
            "LIPONPBGOPN_ABEHDHJCDIL" => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_ABEHDHJCDIL),
            "LIPONPBGOPN_HMNDKFKCGNL" => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_HMNDKFKCGNL),
            "LIPONPBGOPN_FEFDACJCFIL" => ::std::option::Option::Some(CmdOfferingType::LIPONPBGOPN_FEFDACJCFIL),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CmdOfferingType] = &[
        CmdOfferingType::LIPONPBGOPN_NLCDGIPGFDJ,
        CmdOfferingType::LIPONPBGOPN_FLPIHJLMCDM,
        CmdOfferingType::LIPONPBGOPN_HGKELIFKFDP,
        CmdOfferingType::LIPONPBGOPN_FKLKKDCLGEN,
        CmdOfferingType::LIPONPBGOPN_ANEEKCGOAMC,
        CmdOfferingType::LIPONPBGOPN_ABEHDHJCDIL,
        CmdOfferingType::LIPONPBGOPN_HMNDKFKCGNL,
        CmdOfferingType::LIPONPBGOPN_FEFDACJCFIL,
    ];
}

impl ::protobuf::EnumFull for CmdOfferingType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("CmdOfferingType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            CmdOfferingType::LIPONPBGOPN_NLCDGIPGFDJ => 0,
            CmdOfferingType::LIPONPBGOPN_FLPIHJLMCDM => 1,
            CmdOfferingType::LIPONPBGOPN_HGKELIFKFDP => 2,
            CmdOfferingType::LIPONPBGOPN_FKLKKDCLGEN => 3,
            CmdOfferingType::LIPONPBGOPN_ANEEKCGOAMC => 4,
            CmdOfferingType::LIPONPBGOPN_ABEHDHJCDIL => 5,
            CmdOfferingType::LIPONPBGOPN_HMNDKFKCGNL => 6,
            CmdOfferingType::LIPONPBGOPN_FEFDACJCFIL => 7,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for CmdOfferingType {
    fn default() -> Self {
        CmdOfferingType::LIPONPBGOPN_NLCDGIPGFDJ
    }
}

impl CmdOfferingType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<CmdOfferingType>("CmdOfferingType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x15CmdOfferingType.proto*\x80\x02\n\x0fCmdOfferingType\x12\x1b\n\x17L\
    IPONPBGOPN_NLCDGIPGFDJ\x10\0\x12\x1c\n\x17LIPONPBGOPN_FLPIHJLMCDM\x10\
    \x946\x12\x1c\n\x17LIPONPBGOPN_HGKELIFKFDP\x10\x906\x12\x1c\n\x17LIPONPB\
    GOPN_FKLKKDCLGEN\x10\x8d6\x12\x1c\n\x17LIPONPBGOPN_ANEEKCGOAMC\x10\x8b6\
    \x12\x1c\n\x17LIPONPBGOPN_ABEHDHJCDIL\x10\x996\x12\x1c\n\x17LIPONPBGOPN_\
    HMNDKFKCGNL\x10\x9a6\x12\x1c\n\x17LIPONPBGOPN_FEFDACJCFIL\x10\x8a6b\x06p\
    roto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(CmdOfferingType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
