// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CmdPunkLordType.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:CmdPunkLordType)
pub enum CmdPunkLordType {
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_GKJBAODJMJG)
    LCLOAOEHABM_GKJBAODJMJG = 0,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_PCDKANKIKFG)
    LCLOAOEHABM_PCDKANKIKFG = 3255,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_LIJAJDIOANK)
    LCLOAOEHABM_LIJAJDIOANK = 3283,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_JKMFBNMFBCO)
    LCLOAOEHABM_JKMFBNMFBCO = 3247,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_OEKBPDHKJBB)
    LCLOAOEHABM_OEKBPDHKJBB = 3214,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_PHPNCEBNPJJ)
    LCLOAOEHABM_PHPNCEBNPJJ = 3228,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_GMLOHGKDJHO)
    LCLOAOEHABM_GMLOHGKDJHO = 3238,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_CILGGILKLMB)
    LCLOAOEHABM_CILGGILKLMB = 3293,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_CIHGPMHBNAD)
    LCLOAOEHABM_CIHGPMHBNAD = 3280,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_KJOJOKAGDNK)
    LCLOAOEHABM_KJOJOKAGDNK = 3277,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_DJEENMCNCPP)
    LCLOAOEHABM_DJEENMCNCPP = 3262,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_INCAIAJNOFE)
    LCLOAOEHABM_INCAIAJNOFE = 3285,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_LKEDJLFJJKM)
    LCLOAOEHABM_LKEDJLFJJKM = 3211,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_GKBCCMGMGED)
    LCLOAOEHABM_GKBCCMGMGED = 3220,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_LLIBPOHIHLB)
    LCLOAOEHABM_LLIBPOHIHLB = 3245,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_PCNGGCCEKMF)
    LCLOAOEHABM_PCNGGCCEKMF = 3279,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_BIHLEGOMCPK)
    LCLOAOEHABM_BIHLEGOMCPK = 3278,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_OJOAPPOFPOE)
    LCLOAOEHABM_OJOAPPOFPOE = 3209,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_DOHDNPOMJOF)
    LCLOAOEHABM_DOHDNPOMJOF = 3275,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_GDNMGFNINCB)
    LCLOAOEHABM_GDNMGFNINCB = 3213,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_NFHNCCOLMHL)
    LCLOAOEHABM_NFHNCCOLMHL = 3257,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_OMKIOIMMFHD)
    LCLOAOEHABM_OMKIOIMMFHD = 3266,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_FBJADFGIKHN)
    LCLOAOEHABM_FBJADFGIKHN = 3295,
    // @@protoc_insertion_point(enum_value:CmdPunkLordType.LCLOAOEHABM_DLLGFLGBCML)
    LCLOAOEHABM_DLLGFLGBCML = 3286,
}

impl ::protobuf::Enum for CmdPunkLordType {
    const NAME: &'static str = "CmdPunkLordType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CmdPunkLordType> {
        match value {
            0 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_GKJBAODJMJG),
            3255 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_PCDKANKIKFG),
            3283 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_LIJAJDIOANK),
            3247 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_JKMFBNMFBCO),
            3214 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_OEKBPDHKJBB),
            3228 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_PHPNCEBNPJJ),
            3238 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_GMLOHGKDJHO),
            3293 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_CILGGILKLMB),
            3280 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_CIHGPMHBNAD),
            3277 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_KJOJOKAGDNK),
            3262 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_DJEENMCNCPP),
            3285 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_INCAIAJNOFE),
            3211 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_LKEDJLFJJKM),
            3220 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_GKBCCMGMGED),
            3245 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_LLIBPOHIHLB),
            3279 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_PCNGGCCEKMF),
            3278 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_BIHLEGOMCPK),
            3209 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_OJOAPPOFPOE),
            3275 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_DOHDNPOMJOF),
            3213 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_GDNMGFNINCB),
            3257 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_NFHNCCOLMHL),
            3266 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_OMKIOIMMFHD),
            3295 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_FBJADFGIKHN),
            3286 => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_DLLGFLGBCML),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CmdPunkLordType> {
        match str {
            "LCLOAOEHABM_GKJBAODJMJG" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_GKJBAODJMJG),
            "LCLOAOEHABM_PCDKANKIKFG" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_PCDKANKIKFG),
            "LCLOAOEHABM_LIJAJDIOANK" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_LIJAJDIOANK),
            "LCLOAOEHABM_JKMFBNMFBCO" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_JKMFBNMFBCO),
            "LCLOAOEHABM_OEKBPDHKJBB" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_OEKBPDHKJBB),
            "LCLOAOEHABM_PHPNCEBNPJJ" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_PHPNCEBNPJJ),
            "LCLOAOEHABM_GMLOHGKDJHO" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_GMLOHGKDJHO),
            "LCLOAOEHABM_CILGGILKLMB" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_CILGGILKLMB),
            "LCLOAOEHABM_CIHGPMHBNAD" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_CIHGPMHBNAD),
            "LCLOAOEHABM_KJOJOKAGDNK" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_KJOJOKAGDNK),
            "LCLOAOEHABM_DJEENMCNCPP" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_DJEENMCNCPP),
            "LCLOAOEHABM_INCAIAJNOFE" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_INCAIAJNOFE),
            "LCLOAOEHABM_LKEDJLFJJKM" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_LKEDJLFJJKM),
            "LCLOAOEHABM_GKBCCMGMGED" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_GKBCCMGMGED),
            "LCLOAOEHABM_LLIBPOHIHLB" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_LLIBPOHIHLB),
            "LCLOAOEHABM_PCNGGCCEKMF" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_PCNGGCCEKMF),
            "LCLOAOEHABM_BIHLEGOMCPK" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_BIHLEGOMCPK),
            "LCLOAOEHABM_OJOAPPOFPOE" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_OJOAPPOFPOE),
            "LCLOAOEHABM_DOHDNPOMJOF" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_DOHDNPOMJOF),
            "LCLOAOEHABM_GDNMGFNINCB" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_GDNMGFNINCB),
            "LCLOAOEHABM_NFHNCCOLMHL" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_NFHNCCOLMHL),
            "LCLOAOEHABM_OMKIOIMMFHD" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_OMKIOIMMFHD),
            "LCLOAOEHABM_FBJADFGIKHN" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_FBJADFGIKHN),
            "LCLOAOEHABM_DLLGFLGBCML" => ::std::option::Option::Some(CmdPunkLordType::LCLOAOEHABM_DLLGFLGBCML),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CmdPunkLordType] = &[
        CmdPunkLordType::LCLOAOEHABM_GKJBAODJMJG,
        CmdPunkLordType::LCLOAOEHABM_PCDKANKIKFG,
        CmdPunkLordType::LCLOAOEHABM_LIJAJDIOANK,
        CmdPunkLordType::LCLOAOEHABM_JKMFBNMFBCO,
        CmdPunkLordType::LCLOAOEHABM_OEKBPDHKJBB,
        CmdPunkLordType::LCLOAOEHABM_PHPNCEBNPJJ,
        CmdPunkLordType::LCLOAOEHABM_GMLOHGKDJHO,
        CmdPunkLordType::LCLOAOEHABM_CILGGILKLMB,
        CmdPunkLordType::LCLOAOEHABM_CIHGPMHBNAD,
        CmdPunkLordType::LCLOAOEHABM_KJOJOKAGDNK,
        CmdPunkLordType::LCLOAOEHABM_DJEENMCNCPP,
        CmdPunkLordType::LCLOAOEHABM_INCAIAJNOFE,
        CmdPunkLordType::LCLOAOEHABM_LKEDJLFJJKM,
        CmdPunkLordType::LCLOAOEHABM_GKBCCMGMGED,
        CmdPunkLordType::LCLOAOEHABM_LLIBPOHIHLB,
        CmdPunkLordType::LCLOAOEHABM_PCNGGCCEKMF,
        CmdPunkLordType::LCLOAOEHABM_BIHLEGOMCPK,
        CmdPunkLordType::LCLOAOEHABM_OJOAPPOFPOE,
        CmdPunkLordType::LCLOAOEHABM_DOHDNPOMJOF,
        CmdPunkLordType::LCLOAOEHABM_GDNMGFNINCB,
        CmdPunkLordType::LCLOAOEHABM_NFHNCCOLMHL,
        CmdPunkLordType::LCLOAOEHABM_OMKIOIMMFHD,
        CmdPunkLordType::LCLOAOEHABM_FBJADFGIKHN,
        CmdPunkLordType::LCLOAOEHABM_DLLGFLGBCML,
    ];
}

impl ::protobuf::EnumFull for CmdPunkLordType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("CmdPunkLordType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            CmdPunkLordType::LCLOAOEHABM_GKJBAODJMJG => 0,
            CmdPunkLordType::LCLOAOEHABM_PCDKANKIKFG => 1,
            CmdPunkLordType::LCLOAOEHABM_LIJAJDIOANK => 2,
            CmdPunkLordType::LCLOAOEHABM_JKMFBNMFBCO => 3,
            CmdPunkLordType::LCLOAOEHABM_OEKBPDHKJBB => 4,
            CmdPunkLordType::LCLOAOEHABM_PHPNCEBNPJJ => 5,
            CmdPunkLordType::LCLOAOEHABM_GMLOHGKDJHO => 6,
            CmdPunkLordType::LCLOAOEHABM_CILGGILKLMB => 7,
            CmdPunkLordType::LCLOAOEHABM_CIHGPMHBNAD => 8,
            CmdPunkLordType::LCLOAOEHABM_KJOJOKAGDNK => 9,
            CmdPunkLordType::LCLOAOEHABM_DJEENMCNCPP => 10,
            CmdPunkLordType::LCLOAOEHABM_INCAIAJNOFE => 11,
            CmdPunkLordType::LCLOAOEHABM_LKEDJLFJJKM => 12,
            CmdPunkLordType::LCLOAOEHABM_GKBCCMGMGED => 13,
            CmdPunkLordType::LCLOAOEHABM_LLIBPOHIHLB => 14,
            CmdPunkLordType::LCLOAOEHABM_PCNGGCCEKMF => 15,
            CmdPunkLordType::LCLOAOEHABM_BIHLEGOMCPK => 16,
            CmdPunkLordType::LCLOAOEHABM_OJOAPPOFPOE => 17,
            CmdPunkLordType::LCLOAOEHABM_DOHDNPOMJOF => 18,
            CmdPunkLordType::LCLOAOEHABM_GDNMGFNINCB => 19,
            CmdPunkLordType::LCLOAOEHABM_NFHNCCOLMHL => 20,
            CmdPunkLordType::LCLOAOEHABM_OMKIOIMMFHD => 21,
            CmdPunkLordType::LCLOAOEHABM_FBJADFGIKHN => 22,
            CmdPunkLordType::LCLOAOEHABM_DLLGFLGBCML => 23,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for CmdPunkLordType {
    fn default() -> Self {
        CmdPunkLordType::LCLOAOEHABM_GKJBAODJMJG
    }
}

impl CmdPunkLordType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<CmdPunkLordType>("CmdPunkLordType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x15CmdPunkLordType.proto*\xe0\x05\n\x0fCmdPunkLordType\x12\x1b\n\x17L\
    CLOAOEHABM_GKJBAODJMJG\x10\0\x12\x1c\n\x17LCLOAOEHABM_PCDKANKIKFG\x10\
    \xb7\x19\x12\x1c\n\x17LCLOAOEHABM_LIJAJDIOANK\x10\xd3\x19\x12\x1c\n\x17L\
    CLOAOEHABM_JKMFBNMFBCO\x10\xaf\x19\x12\x1c\n\x17LCLOAOEHABM_OEKBPDHKJBB\
    \x10\x8e\x19\x12\x1c\n\x17LCLOAOEHABM_PHPNCEBNPJJ\x10\x9c\x19\x12\x1c\n\
    \x17LCLOAOEHABM_GMLOHGKDJHO\x10\xa6\x19\x12\x1c\n\x17LCLOAOEHABM_CILGGIL\
    KLMB\x10\xdd\x19\x12\x1c\n\x17LCLOAOEHABM_CIHGPMHBNAD\x10\xd0\x19\x12\
    \x1c\n\x17LCLOAOEHABM_KJOJOKAGDNK\x10\xcd\x19\x12\x1c\n\x17LCLOAOEHABM_D\
    JEENMCNCPP\x10\xbe\x19\x12\x1c\n\x17LCLOAOEHABM_INCAIAJNOFE\x10\xd5\x19\
    \x12\x1c\n\x17LCLOAOEHABM_LKEDJLFJJKM\x10\x8b\x19\x12\x1c\n\x17LCLOAOEHA\
    BM_GKBCCMGMGED\x10\x94\x19\x12\x1c\n\x17LCLOAOEHABM_LLIBPOHIHLB\x10\xad\
    \x19\x12\x1c\n\x17LCLOAOEHABM_PCNGGCCEKMF\x10\xcf\x19\x12\x1c\n\x17LCLOA\
    OEHABM_BIHLEGOMCPK\x10\xce\x19\x12\x1c\n\x17LCLOAOEHABM_OJOAPPOFPOE\x10\
    \x89\x19\x12\x1c\n\x17LCLOAOEHABM_DOHDNPOMJOF\x10\xcb\x19\x12\x1c\n\x17L\
    CLOAOEHABM_GDNMGFNINCB\x10\x8d\x19\x12\x1c\n\x17LCLOAOEHABM_NFHNCCOLMHL\
    \x10\xb9\x19\x12\x1c\n\x17LCLOAOEHABM_OMKIOIMMFHD\x10\xc2\x19\x12\x1c\n\
    \x17LCLOAOEHABM_FBJADFGIKHN\x10\xdf\x19\x12\x1c\n\x17LCLOAOEHABM_DLLGFLG\
    BCML\x10\xd6\x19b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(CmdPunkLordType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
