// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CmdStrongChallengeActivityType.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:CmdStrongChallengeActivityType)
pub enum CmdStrongChallengeActivityType {
    // @@protoc_insertion_point(enum_value:CmdStrongChallengeActivityType.CmdStrongChallengeActivityType_MNFEPONEDDJ)
    CmdStrongChallengeActivityType_MNFEPONEDDJ = 0,
    // @@protoc_insertion_point(enum_value:CmdStrongChallengeActivityType.CmdStrongChallengeActivityType_JNEIGELBPBO)
    CmdStrongChallengeActivityType_JNEIGELBPBO = 6604,
    // @@protoc_insertion_point(enum_value:CmdStrongChallengeActivityType.CmdStrongChallengeActivityType_CJLLLFCDMEF)
    CmdStrongChallengeActivityType_CJLLLFCDMEF = 6681,
    // @@protoc_insertion_point(enum_value:CmdStrongChallengeActivityType.CmdStrongChallengeActivityType_BEIDKFOLONM)
    CmdStrongChallengeActivityType_BEIDKFOLONM = 6624,
    // @@protoc_insertion_point(enum_value:CmdStrongChallengeActivityType.CmdStrongChallengeActivityType_HMCDGEGPAPI)
    CmdStrongChallengeActivityType_HMCDGEGPAPI = 6635,
    // @@protoc_insertion_point(enum_value:CmdStrongChallengeActivityType.CmdStrongChallengeActivityType_FMEPDPDCBGJ)
    CmdStrongChallengeActivityType_FMEPDPDCBGJ = 6683,
}

impl ::protobuf::Enum for CmdStrongChallengeActivityType {
    const NAME: &'static str = "CmdStrongChallengeActivityType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CmdStrongChallengeActivityType> {
        match value {
            0 => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_MNFEPONEDDJ),
            6604 => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_JNEIGELBPBO),
            6681 => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_CJLLLFCDMEF),
            6624 => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_BEIDKFOLONM),
            6635 => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_HMCDGEGPAPI),
            6683 => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_FMEPDPDCBGJ),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CmdStrongChallengeActivityType> {
        match str {
            "CmdStrongChallengeActivityType_MNFEPONEDDJ" => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_MNFEPONEDDJ),
            "CmdStrongChallengeActivityType_JNEIGELBPBO" => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_JNEIGELBPBO),
            "CmdStrongChallengeActivityType_CJLLLFCDMEF" => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_CJLLLFCDMEF),
            "CmdStrongChallengeActivityType_BEIDKFOLONM" => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_BEIDKFOLONM),
            "CmdStrongChallengeActivityType_HMCDGEGPAPI" => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_HMCDGEGPAPI),
            "CmdStrongChallengeActivityType_FMEPDPDCBGJ" => ::std::option::Option::Some(CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_FMEPDPDCBGJ),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CmdStrongChallengeActivityType] = &[
        CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_MNFEPONEDDJ,
        CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_JNEIGELBPBO,
        CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_CJLLLFCDMEF,
        CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_BEIDKFOLONM,
        CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_HMCDGEGPAPI,
        CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_FMEPDPDCBGJ,
    ];
}

impl ::protobuf::EnumFull for CmdStrongChallengeActivityType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("CmdStrongChallengeActivityType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_MNFEPONEDDJ => 0,
            CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_JNEIGELBPBO => 1,
            CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_CJLLLFCDMEF => 2,
            CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_BEIDKFOLONM => 3,
            CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_HMCDGEGPAPI => 4,
            CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_FMEPDPDCBGJ => 5,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for CmdStrongChallengeActivityType {
    fn default() -> Self {
        CmdStrongChallengeActivityType::CmdStrongChallengeActivityType_MNFEPONEDDJ
    }
}

impl CmdStrongChallengeActivityType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<CmdStrongChallengeActivityType>("CmdStrongChallengeActivityType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n$CmdStrongChallengeActivityType.proto*\xc5\x02\n\x1eCmdStrongChallenge\
    ActivityType\x12.\n*CmdStrongChallengeActivityType_MNFEPONEDDJ\x10\0\x12\
    /\n*CmdStrongChallengeActivityType_JNEIGELBPBO\x10\xcc3\x12/\n*CmdStrong\
    ChallengeActivityType_CJLLLFCDMEF\x10\x994\x12/\n*CmdStrongChallengeActi\
    vityType_BEIDKFOLONM\x10\xe03\x12/\n*CmdStrongChallengeActivityType_HMCD\
    GEGPAPI\x10\xeb3\x12/\n*CmdStrongChallengeActivityType_FMEPDPDCBGJ\x10\
    \x9b4b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(CmdStrongChallengeActivityType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
