// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `COOKLLDMALC.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:COOKLLDMALC)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct COOKLLDMALC {
    // message fields
    // @@protoc_insertion_point(field:COOKLLDMALC.passenger_id)
    pub passenger_id: u32,
    // @@protoc_insertion_point(field:COOKLLDMALC.FEFJDEGCANA)
    pub FEFJDEGCANA: ::std::vec::Vec<super::LEJNMOLIJOJ::LEJNMOLIJOJ>,
    // special fields
    // @@protoc_insertion_point(special_field:COOKLLDMALC.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a COOKLLDMALC {
    fn default() -> &'a COOKLLDMALC {
        <COOKLLDMALC as ::protobuf::Message>::default_instance()
    }
}

impl COOKLLDMALC {
    pub fn new() -> COOKLLDMALC {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "passenger_id",
            |m: &COOKLLDMALC| { &m.passenger_id },
            |m: &mut COOKLLDMALC| { &mut m.passenger_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "FEFJDEGCANA",
            |m: &COOKLLDMALC| { &m.FEFJDEGCANA },
            |m: &mut COOKLLDMALC| { &mut m.FEFJDEGCANA },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<COOKLLDMALC>(
            "COOKLLDMALC",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for COOKLLDMALC {
    const NAME: &'static str = "COOKLLDMALC";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                24 => {
                    self.passenger_id = is.read_uint32()?;
                },
                114 => {
                    self.FEFJDEGCANA.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.passenger_id != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.passenger_id);
        }
        for value in &self.FEFJDEGCANA {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.passenger_id != 0 {
            os.write_uint32(3, self.passenger_id)?;
        }
        for v in &self.FEFJDEGCANA {
            ::protobuf::rt::write_message_field_with_cached_size(14, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> COOKLLDMALC {
        COOKLLDMALC::new()
    }

    fn clear(&mut self) {
        self.passenger_id = 0;
        self.FEFJDEGCANA.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static COOKLLDMALC {
        static instance: COOKLLDMALC = COOKLLDMALC {
            passenger_id: 0,
            FEFJDEGCANA: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for COOKLLDMALC {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("COOKLLDMALC").unwrap()).clone()
    }
}

impl ::std::fmt::Display for COOKLLDMALC {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for COOKLLDMALC {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11COOKLLDMALC.proto\x1a\x11LEJNMOLIJOJ.proto\"`\n\x0bCOOKLLDMALC\x12\
    !\n\x0cpassenger_id\x18\x03\x20\x01(\rR\x0bpassengerId\x12.\n\x0bFEFJDEG\
    CANA\x18\x0e\x20\x03(\x0b2\x0c.LEJNMOLIJOJR\x0bFEFJDEGCANAb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::LEJNMOLIJOJ::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(COOKLLDMALC::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
