// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `DBANAPEAALP.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:DBANAPEAALP)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DBANAPEAALP {
    // message fields
    // @@protoc_insertion_point(field:DBANAPEAALP.GAEGMBIOGOH)
    pub GAEGMBIOGOH: ::std::vec::Vec<super::FHABEIKAFBO::FHABEIKAFBO>,
    // @@protoc_insertion_point(field:DBANAPEAALP.NEBOJOCKGCL)
    pub NEBOJOCKGCL: ::std::vec::Vec<super::IOPMFBIAFJH::IOPMFBIAFJH>,
    // @@protoc_insertion_point(field:DBANAPEAALP.ANIHPCKNGBM)
    pub ANIHPCKNGBM: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:DBANAPEAALP.HNEPOEDCIDK)
    pub HNEPOEDCIDK: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:DBANAPEAALP.EJBGGJONBOL)
    pub EJBGGJONBOL: ::std::vec::Vec<super::IKAMMKLBOCO::IKAMMKLBOCO>,
    // @@protoc_insertion_point(field:DBANAPEAALP.BOKMHANJBPO)
    pub BOKMHANJBPO: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:DBANAPEAALP.MCFONOPKOKD)
    pub MCFONOPKOKD: ::std::vec::Vec<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:DBANAPEAALP.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DBANAPEAALP {
    fn default() -> &'a DBANAPEAALP {
        <DBANAPEAALP as ::protobuf::Message>::default_instance()
    }
}

impl DBANAPEAALP {
    pub fn new() -> DBANAPEAALP {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "GAEGMBIOGOH",
            |m: &DBANAPEAALP| { &m.GAEGMBIOGOH },
            |m: &mut DBANAPEAALP| { &mut m.GAEGMBIOGOH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "NEBOJOCKGCL",
            |m: &DBANAPEAALP| { &m.NEBOJOCKGCL },
            |m: &mut DBANAPEAALP| { &mut m.NEBOJOCKGCL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "ANIHPCKNGBM",
            |m: &DBANAPEAALP| { &m.ANIHPCKNGBM },
            |m: &mut DBANAPEAALP| { &mut m.ANIHPCKNGBM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "HNEPOEDCIDK",
            |m: &DBANAPEAALP| { &m.HNEPOEDCIDK },
            |m: &mut DBANAPEAALP| { &mut m.HNEPOEDCIDK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "EJBGGJONBOL",
            |m: &DBANAPEAALP| { &m.EJBGGJONBOL },
            |m: &mut DBANAPEAALP| { &mut m.EJBGGJONBOL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "BOKMHANJBPO",
            |m: &DBANAPEAALP| { &m.BOKMHANJBPO },
            |m: &mut DBANAPEAALP| { &mut m.BOKMHANJBPO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "MCFONOPKOKD",
            |m: &DBANAPEAALP| { &m.MCFONOPKOKD },
            |m: &mut DBANAPEAALP| { &mut m.MCFONOPKOKD },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DBANAPEAALP>(
            "DBANAPEAALP",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DBANAPEAALP {
    const NAME: &'static str = "DBANAPEAALP";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                106 => {
                    self.GAEGMBIOGOH.push(is.read_message()?);
                },
                42 => {
                    self.NEBOJOCKGCL.push(is.read_message()?);
                },
                82 => {
                    is.read_repeated_packed_uint32_into(&mut self.ANIHPCKNGBM)?;
                },
                80 => {
                    self.ANIHPCKNGBM.push(is.read_uint32()?);
                },
                18 => {
                    is.read_repeated_packed_uint32_into(&mut self.HNEPOEDCIDK)?;
                },
                16 => {
                    self.HNEPOEDCIDK.push(is.read_uint32()?);
                },
                34 => {
                    self.EJBGGJONBOL.push(is.read_message()?);
                },
                10 => {
                    is.read_repeated_packed_uint32_into(&mut self.BOKMHANJBPO)?;
                },
                8 => {
                    self.BOKMHANJBPO.push(is.read_uint32()?);
                },
                122 => {
                    is.read_repeated_packed_uint32_into(&mut self.MCFONOPKOKD)?;
                },
                120 => {
                    self.MCFONOPKOKD.push(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.GAEGMBIOGOH {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.NEBOJOCKGCL {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::vec_packed_uint32_size(10, &self.ANIHPCKNGBM);
        my_size += ::protobuf::rt::vec_packed_uint32_size(2, &self.HNEPOEDCIDK);
        for value in &self.EJBGGJONBOL {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::vec_packed_uint32_size(1, &self.BOKMHANJBPO);
        my_size += ::protobuf::rt::vec_packed_uint32_size(15, &self.MCFONOPKOKD);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.GAEGMBIOGOH {
            ::protobuf::rt::write_message_field_with_cached_size(13, v, os)?;
        };
        for v in &self.NEBOJOCKGCL {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        };
        os.write_repeated_packed_uint32(10, &self.ANIHPCKNGBM)?;
        os.write_repeated_packed_uint32(2, &self.HNEPOEDCIDK)?;
        for v in &self.EJBGGJONBOL {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        os.write_repeated_packed_uint32(1, &self.BOKMHANJBPO)?;
        os.write_repeated_packed_uint32(15, &self.MCFONOPKOKD)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DBANAPEAALP {
        DBANAPEAALP::new()
    }

    fn clear(&mut self) {
        self.GAEGMBIOGOH.clear();
        self.NEBOJOCKGCL.clear();
        self.ANIHPCKNGBM.clear();
        self.HNEPOEDCIDK.clear();
        self.EJBGGJONBOL.clear();
        self.BOKMHANJBPO.clear();
        self.MCFONOPKOKD.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DBANAPEAALP {
        static instance: DBANAPEAALP = DBANAPEAALP {
            GAEGMBIOGOH: ::std::vec::Vec::new(),
            NEBOJOCKGCL: ::std::vec::Vec::new(),
            ANIHPCKNGBM: ::std::vec::Vec::new(),
            HNEPOEDCIDK: ::std::vec::Vec::new(),
            EJBGGJONBOL: ::std::vec::Vec::new(),
            BOKMHANJBPO: ::std::vec::Vec::new(),
            MCFONOPKOKD: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DBANAPEAALP {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DBANAPEAALP").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DBANAPEAALP {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DBANAPEAALP {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11DBANAPEAALP.proto\x1a\x11FHABEIKAFBO.proto\x1a\x11IKAMMKLBOCO.prot\
    o\x1a\x11IOPMFBIAFJH.proto\"\xa5\x02\n\x0bDBANAPEAALP\x12.\n\x0bGAEGMBIO\
    GOH\x18\r\x20\x03(\x0b2\x0c.FHABEIKAFBOR\x0bGAEGMBIOGOH\x12.\n\x0bNEBOJO\
    CKGCL\x18\x05\x20\x03(\x0b2\x0c.IOPMFBIAFJHR\x0bNEBOJOCKGCL\x12\x20\n\
    \x0bANIHPCKNGBM\x18\n\x20\x03(\rR\x0bANIHPCKNGBM\x12\x20\n\x0bHNEPOEDCID\
    K\x18\x02\x20\x03(\rR\x0bHNEPOEDCIDK\x12.\n\x0bEJBGGJONBOL\x18\x04\x20\
    \x03(\x0b2\x0c.IKAMMKLBOCOR\x0bEJBGGJONBOL\x12\x20\n\x0bBOKMHANJBPO\x18\
    \x01\x20\x03(\rR\x0bBOKMHANJBPO\x12\x20\n\x0bMCFONOPKOKD\x18\x0f\x20\x03\
    (\rR\x0bMCFONOPKOKDb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::FHABEIKAFBO::file_descriptor().clone());
            deps.push(super::IKAMMKLBOCO::file_descriptor().clone());
            deps.push(super::IOPMFBIAFJH::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(DBANAPEAALP::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
