// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `DNECEONNCGB.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:DNECEONNCGB)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DNECEONNCGB {
    // message fields
    // @@protoc_insertion_point(field:DNECEONNCGB.BFHFPLGKKHN)
    pub BFHFPLGKKHN: u32,
    // @@protoc_insertion_point(field:DNECEONNCGB.FJEJGMAEAMK)
    pub FJEJGMAEAMK: u32,
    // @@protoc_insertion_point(field:DNECEONNCGB.CCGPIMDMGJE)
    pub CCGPIMDMGJE: ::protobuf::MessageField<super::KNFMIKPCGOP::KNFMIKPCGOP>,
    // @@protoc_insertion_point(field:DNECEONNCGB.HEJOPJMKHOD)
    pub HEJOPJMKHOD: ::std::vec::Vec<super::EAJJPMDKNJB::EAJJPMDKNJB>,
    // @@protoc_insertion_point(field:DNECEONNCGB.PGOKEBJKPBP)
    pub PGOKEBJKPBP: u32,
    // @@protoc_insertion_point(field:DNECEONNCGB.CHGOLKCKCIK)
    pub CHGOLKCKCIK: u32,
    // @@protoc_insertion_point(field:DNECEONNCGB.MJCMGDGCBFG)
    pub MJCMGDGCBFG: ::protobuf::MessageField<super::KNFMIKPCGOP::KNFMIKPCGOP>,
    // @@protoc_insertion_point(field:DNECEONNCGB.OKDACFDFKBE)
    pub OKDACFDFKBE: ::std::collections::HashMap<u32, u32>,
    // @@protoc_insertion_point(field:DNECEONNCGB.HDAOMOLAAOP)
    pub HDAOMOLAAOP: u32,
    // @@protoc_insertion_point(field:DNECEONNCGB.GAIPFENALEF)
    pub GAIPFENALEF: ::protobuf::MessageField<super::KNFMIKPCGOP::KNFMIKPCGOP>,
    // special fields
    // @@protoc_insertion_point(special_field:DNECEONNCGB.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DNECEONNCGB {
    fn default() -> &'a DNECEONNCGB {
        <DNECEONNCGB as ::protobuf::Message>::default_instance()
    }
}

impl DNECEONNCGB {
    pub fn new() -> DNECEONNCGB {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(10);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "BFHFPLGKKHN",
            |m: &DNECEONNCGB| { &m.BFHFPLGKKHN },
            |m: &mut DNECEONNCGB| { &mut m.BFHFPLGKKHN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "FJEJGMAEAMK",
            |m: &DNECEONNCGB| { &m.FJEJGMAEAMK },
            |m: &mut DNECEONNCGB| { &mut m.FJEJGMAEAMK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::KNFMIKPCGOP::KNFMIKPCGOP>(
            "CCGPIMDMGJE",
            |m: &DNECEONNCGB| { &m.CCGPIMDMGJE },
            |m: &mut DNECEONNCGB| { &mut m.CCGPIMDMGJE },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "HEJOPJMKHOD",
            |m: &DNECEONNCGB| { &m.HEJOPJMKHOD },
            |m: &mut DNECEONNCGB| { &mut m.HEJOPJMKHOD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "PGOKEBJKPBP",
            |m: &DNECEONNCGB| { &m.PGOKEBJKPBP },
            |m: &mut DNECEONNCGB| { &mut m.PGOKEBJKPBP },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CHGOLKCKCIK",
            |m: &DNECEONNCGB| { &m.CHGOLKCKCIK },
            |m: &mut DNECEONNCGB| { &mut m.CHGOLKCKCIK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::KNFMIKPCGOP::KNFMIKPCGOP>(
            "MJCMGDGCBFG",
            |m: &DNECEONNCGB| { &m.MJCMGDGCBFG },
            |m: &mut DNECEONNCGB| { &mut m.MJCMGDGCBFG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "OKDACFDFKBE",
            |m: &DNECEONNCGB| { &m.OKDACFDFKBE },
            |m: &mut DNECEONNCGB| { &mut m.OKDACFDFKBE },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "HDAOMOLAAOP",
            |m: &DNECEONNCGB| { &m.HDAOMOLAAOP },
            |m: &mut DNECEONNCGB| { &mut m.HDAOMOLAAOP },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::KNFMIKPCGOP::KNFMIKPCGOP>(
            "GAIPFENALEF",
            |m: &DNECEONNCGB| { &m.GAIPFENALEF },
            |m: &mut DNECEONNCGB| { &mut m.GAIPFENALEF },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DNECEONNCGB>(
            "DNECEONNCGB",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DNECEONNCGB {
    const NAME: &'static str = "DNECEONNCGB";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                96 => {
                    self.BFHFPLGKKHN = is.read_uint32()?;
                },
                8 => {
                    self.FJEJGMAEAMK = is.read_uint32()?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.CCGPIMDMGJE)?;
                },
                26 => {
                    self.HEJOPJMKHOD.push(is.read_message()?);
                },
                120 => {
                    self.PGOKEBJKPBP = is.read_uint32()?;
                },
                88 => {
                    self.CHGOLKCKCIK = is.read_uint32()?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.MJCMGDGCBFG)?;
                },
                114 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            8 => key = is.read_uint32()?,
                            16 => value = is.read_uint32()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.OKDACFDFKBE.insert(key, value);
                },
                104 => {
                    self.HDAOMOLAAOP = is.read_uint32()?;
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.GAIPFENALEF)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.BFHFPLGKKHN != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.BFHFPLGKKHN);
        }
        if self.FJEJGMAEAMK != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.FJEJGMAEAMK);
        }
        if let Some(v) = self.CCGPIMDMGJE.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.HEJOPJMKHOD {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.PGOKEBJKPBP != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.PGOKEBJKPBP);
        }
        if self.CHGOLKCKCIK != 0 {
            my_size += ::protobuf::rt::uint32_size(11, self.CHGOLKCKCIK);
        }
        if let Some(v) = self.MJCMGDGCBFG.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for (k, v) in &self.OKDACFDFKBE {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::uint32_size(1, *k);
            entry_size += ::protobuf::rt::uint32_size(2, *v);
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        if self.HDAOMOLAAOP != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.HDAOMOLAAOP);
        }
        if let Some(v) = self.GAIPFENALEF.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.BFHFPLGKKHN != 0 {
            os.write_uint32(12, self.BFHFPLGKKHN)?;
        }
        if self.FJEJGMAEAMK != 0 {
            os.write_uint32(1, self.FJEJGMAEAMK)?;
        }
        if let Some(v) = self.CCGPIMDMGJE.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        for v in &self.HEJOPJMKHOD {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        if self.PGOKEBJKPBP != 0 {
            os.write_uint32(15, self.PGOKEBJKPBP)?;
        }
        if self.CHGOLKCKCIK != 0 {
            os.write_uint32(11, self.CHGOLKCKCIK)?;
        }
        if let Some(v) = self.MJCMGDGCBFG.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        for (k, v) in &self.OKDACFDFKBE {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::uint32_size(1, *k);
            entry_size += ::protobuf::rt::uint32_size(2, *v);
            os.write_raw_varint32(114)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_uint32(1, *k)?;
            os.write_uint32(2, *v)?;
        };
        if self.HDAOMOLAAOP != 0 {
            os.write_uint32(13, self.HDAOMOLAAOP)?;
        }
        if let Some(v) = self.GAIPFENALEF.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DNECEONNCGB {
        DNECEONNCGB::new()
    }

    fn clear(&mut self) {
        self.BFHFPLGKKHN = 0;
        self.FJEJGMAEAMK = 0;
        self.CCGPIMDMGJE.clear();
        self.HEJOPJMKHOD.clear();
        self.PGOKEBJKPBP = 0;
        self.CHGOLKCKCIK = 0;
        self.MJCMGDGCBFG.clear();
        self.OKDACFDFKBE.clear();
        self.HDAOMOLAAOP = 0;
        self.GAIPFENALEF.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DNECEONNCGB {
        static instance: ::protobuf::rt::Lazy<DNECEONNCGB> = ::protobuf::rt::Lazy::new();
        instance.get(DNECEONNCGB::new)
    }
}

impl ::protobuf::MessageFull for DNECEONNCGB {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DNECEONNCGB").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DNECEONNCGB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DNECEONNCGB {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11DNECEONNCGB.proto\x1a\x11EAJJPMDKNJB.proto\x1a\x11KNFMIKPCGOP.prot\
    o\"\xf8\x03\n\x0bDNECEONNCGB\x12\x20\n\x0bBFHFPLGKKHN\x18\x0c\x20\x01(\r\
    R\x0bBFHFPLGKKHN\x12\x20\n\x0bFJEJGMAEAMK\x18\x01\x20\x01(\rR\x0bFJEJGMA\
    EAMK\x12.\n\x0bCCGPIMDMGJE\x18\x06\x20\x01(\x0b2\x0c.KNFMIKPCGOPR\x0bCCG\
    PIMDMGJE\x12.\n\x0bHEJOPJMKHOD\x18\x03\x20\x03(\x0b2\x0c.EAJJPMDKNJBR\
    \x0bHEJOPJMKHOD\x12\x20\n\x0bPGOKEBJKPBP\x18\x0f\x20\x01(\rR\x0bPGOKEBJK\
    PBP\x12\x20\n\x0bCHGOLKCKCIK\x18\x0b\x20\x01(\rR\x0bCHGOLKCKCIK\x12.\n\
    \x0bMJCMGDGCBFG\x18\x08\x20\x01(\x0b2\x0c.KNFMIKPCGOPR\x0bMJCMGDGCBFG\
    \x12?\n\x0bOKDACFDFKBE\x18\x0e\x20\x03(\x0b2\x1d.DNECEONNCGB.OKDACFDFKBE\
    EntryR\x0bOKDACFDFKBE\x12\x20\n\x0bHDAOMOLAAOP\x18\r\x20\x01(\rR\x0bHDAO\
    MOLAAOP\x12.\n\x0bGAIPFENALEF\x18\n\x20\x01(\x0b2\x0c.KNFMIKPCGOPR\x0bGA\
    IPFENALEF\x1a>\n\x10OKDACFDFKBEEntry\x12\x10\n\x03key\x18\x01\x20\x01(\r\
    R\x03key\x12\x14\n\x05value\x18\x02\x20\x01(\rR\x05value:\x028\x01b\x06p\
    roto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::EAJJPMDKNJB::file_descriptor().clone());
            deps.push(super::KNFMIKPCGOP::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(DNECEONNCGB::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
