// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `FOEEKODAJMB.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:FOEEKODAJMB)
pub enum FOEEKODAJMB {
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_MNFEPONEDDJ)
    FOEEKODAJMB_MNFEPONEDDJ = 0,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_CNMNACEBAFP)
    FOEEKODAJMB_CNMNACEBAFP = 1,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_ABNMCFMGIOB)
    FOEEKODAJMB_ABNMCFMGIOB = 2,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_DLMICOPKFCO)
    FOEEKODAJMB_DLMICOPKFCO = 3,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_BMCMPHDKBDI)
    FOEEKODAJMB_BMCMPHDKBDI = 4,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_BJOENIFAFLL)
    FOEEKODAJMB_BJOENIFAFLL = 5,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_HIJCGFONFFL)
    FOEEKODAJMB_HIJCGFONFFL = 6,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_OJEPGKBPPIP)
    FOEEKODAJMB_OJEPGKBPPIP = 7,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_BDJFLEJPDOG)
    FOEEKODAJMB_BDJFLEJPDOG = 8,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_shop_sync_info)
    FOEEKODAJMB_shop_sync_info = 9,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_KDGMIMJEAFF)
    FOEEKODAJMB_KDGMIMJEAFF = 10,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_NBDCGPIOGKE)
    FOEEKODAJMB_NBDCGPIOGKE = 11,
    // @@protoc_insertion_point(enum_value:FOEEKODAJMB.FOEEKODAJMB_JEENJLLDDOC)
    FOEEKODAJMB_JEENJLLDDOC = 12,
}

impl ::protobuf::Enum for FOEEKODAJMB {
    const NAME: &'static str = "FOEEKODAJMB";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FOEEKODAJMB> {
        match value {
            0 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_MNFEPONEDDJ),
            1 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_CNMNACEBAFP),
            2 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_ABNMCFMGIOB),
            3 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_DLMICOPKFCO),
            4 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_BMCMPHDKBDI),
            5 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_BJOENIFAFLL),
            6 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_HIJCGFONFFL),
            7 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_OJEPGKBPPIP),
            8 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_BDJFLEJPDOG),
            9 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_shop_sync_info),
            10 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_KDGMIMJEAFF),
            11 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_NBDCGPIOGKE),
            12 => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_JEENJLLDDOC),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<FOEEKODAJMB> {
        match str {
            "FOEEKODAJMB_MNFEPONEDDJ" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_MNFEPONEDDJ),
            "FOEEKODAJMB_CNMNACEBAFP" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_CNMNACEBAFP),
            "FOEEKODAJMB_ABNMCFMGIOB" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_ABNMCFMGIOB),
            "FOEEKODAJMB_DLMICOPKFCO" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_DLMICOPKFCO),
            "FOEEKODAJMB_BMCMPHDKBDI" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_BMCMPHDKBDI),
            "FOEEKODAJMB_BJOENIFAFLL" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_BJOENIFAFLL),
            "FOEEKODAJMB_HIJCGFONFFL" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_HIJCGFONFFL),
            "FOEEKODAJMB_OJEPGKBPPIP" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_OJEPGKBPPIP),
            "FOEEKODAJMB_BDJFLEJPDOG" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_BDJFLEJPDOG),
            "FOEEKODAJMB_shop_sync_info" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_shop_sync_info),
            "FOEEKODAJMB_KDGMIMJEAFF" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_KDGMIMJEAFF),
            "FOEEKODAJMB_NBDCGPIOGKE" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_NBDCGPIOGKE),
            "FOEEKODAJMB_JEENJLLDDOC" => ::std::option::Option::Some(FOEEKODAJMB::FOEEKODAJMB_JEENJLLDDOC),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [FOEEKODAJMB] = &[
        FOEEKODAJMB::FOEEKODAJMB_MNFEPONEDDJ,
        FOEEKODAJMB::FOEEKODAJMB_CNMNACEBAFP,
        FOEEKODAJMB::FOEEKODAJMB_ABNMCFMGIOB,
        FOEEKODAJMB::FOEEKODAJMB_DLMICOPKFCO,
        FOEEKODAJMB::FOEEKODAJMB_BMCMPHDKBDI,
        FOEEKODAJMB::FOEEKODAJMB_BJOENIFAFLL,
        FOEEKODAJMB::FOEEKODAJMB_HIJCGFONFFL,
        FOEEKODAJMB::FOEEKODAJMB_OJEPGKBPPIP,
        FOEEKODAJMB::FOEEKODAJMB_BDJFLEJPDOG,
        FOEEKODAJMB::FOEEKODAJMB_shop_sync_info,
        FOEEKODAJMB::FOEEKODAJMB_KDGMIMJEAFF,
        FOEEKODAJMB::FOEEKODAJMB_NBDCGPIOGKE,
        FOEEKODAJMB::FOEEKODAJMB_JEENJLLDDOC,
    ];
}

impl ::protobuf::EnumFull for FOEEKODAJMB {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("FOEEKODAJMB").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for FOEEKODAJMB {
    fn default() -> Self {
        FOEEKODAJMB::FOEEKODAJMB_MNFEPONEDDJ
    }
}

impl FOEEKODAJMB {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<FOEEKODAJMB>("FOEEKODAJMB")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11FOEEKODAJMB.proto*\x89\x03\n\x0bFOEEKODAJMB\x12\x1b\n\x17FOEEKODAJ\
    MB_MNFEPONEDDJ\x10\0\x12\x1b\n\x17FOEEKODAJMB_CNMNACEBAFP\x10\x01\x12\
    \x1b\n\x17FOEEKODAJMB_ABNMCFMGIOB\x10\x02\x12\x1b\n\x17FOEEKODAJMB_DLMIC\
    OPKFCO\x10\x03\x12\x1b\n\x17FOEEKODAJMB_BMCMPHDKBDI\x10\x04\x12\x1b\n\
    \x17FOEEKODAJMB_BJOENIFAFLL\x10\x05\x12\x1b\n\x17FOEEKODAJMB_HIJCGFONFFL\
    \x10\x06\x12\x1b\n\x17FOEEKODAJMB_OJEPGKBPPIP\x10\x07\x12\x1b\n\x17FOEEK\
    ODAJMB_BDJFLEJPDOG\x10\x08\x12\x1e\n\x1aFOEEKODAJMB_shop_sync_info\x10\t\
    \x12\x1b\n\x17FOEEKODAJMB_KDGMIMJEAFF\x10\n\x12\x1b\n\x17FOEEKODAJMB_NBD\
    CGPIOGKE\x10\x0b\x12\x1b\n\x17FOEEKODAJMB_JEENJLLDDOC\x10\x0cb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(FOEEKODAJMB::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
