// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `GamecoreConfig.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:GamecoreConfig)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GamecoreConfig {
    // message fields
    // @@protoc_insertion_point(field:GamecoreConfig.is_skip_verify)
    pub is_skip_verify: bool,
    // @@protoc_insertion_point(field:GamecoreConfig.max_turn_cnt)
    pub max_turn_cnt: u32,
    // @@protoc_insertion_point(field:GamecoreConfig.is_auto_fight)
    pub is_auto_fight: bool,
    // @@protoc_insertion_point(field:GamecoreConfig.csv_path)
    pub csv_path: ::std::string::String,
    // @@protoc_insertion_point(field:GamecoreConfig.is_battle_simulator_auto_fight)
    pub is_battle_simulator_auto_fight: bool,
    // @@protoc_insertion_point(field:GamecoreConfig.FJKKJGGAFIA)
    pub FJKKJGGAFIA: bool,
    // @@protoc_insertion_point(field:GamecoreConfig.JFBIBFGIDME)
    pub JFBIBFGIDME: u32,
    // special fields
    // @@protoc_insertion_point(special_field:GamecoreConfig.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GamecoreConfig {
    fn default() -> &'a GamecoreConfig {
        <GamecoreConfig as ::protobuf::Message>::default_instance()
    }
}

impl GamecoreConfig {
    pub fn new() -> GamecoreConfig {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_skip_verify",
            |m: &GamecoreConfig| { &m.is_skip_verify },
            |m: &mut GamecoreConfig| { &mut m.is_skip_verify },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "max_turn_cnt",
            |m: &GamecoreConfig| { &m.max_turn_cnt },
            |m: &mut GamecoreConfig| { &mut m.max_turn_cnt },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_auto_fight",
            |m: &GamecoreConfig| { &m.is_auto_fight },
            |m: &mut GamecoreConfig| { &mut m.is_auto_fight },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "csv_path",
            |m: &GamecoreConfig| { &m.csv_path },
            |m: &mut GamecoreConfig| { &mut m.csv_path },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_battle_simulator_auto_fight",
            |m: &GamecoreConfig| { &m.is_battle_simulator_auto_fight },
            |m: &mut GamecoreConfig| { &mut m.is_battle_simulator_auto_fight },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "FJKKJGGAFIA",
            |m: &GamecoreConfig| { &m.FJKKJGGAFIA },
            |m: &mut GamecoreConfig| { &mut m.FJKKJGGAFIA },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JFBIBFGIDME",
            |m: &GamecoreConfig| { &m.JFBIBFGIDME },
            |m: &mut GamecoreConfig| { &mut m.JFBIBFGIDME },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GamecoreConfig>(
            "GamecoreConfig",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GamecoreConfig {
    const NAME: &'static str = "GamecoreConfig";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.is_skip_verify = is.read_bool()?;
                },
                16 => {
                    self.max_turn_cnt = is.read_uint32()?;
                },
                24 => {
                    self.is_auto_fight = is.read_bool()?;
                },
                34 => {
                    self.csv_path = is.read_string()?;
                },
                40 => {
                    self.is_battle_simulator_auto_fight = is.read_bool()?;
                },
                48 => {
                    self.FJKKJGGAFIA = is.read_bool()?;
                },
                56 => {
                    self.JFBIBFGIDME = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.is_skip_verify != false {
            my_size += 1 + 1;
        }
        if self.max_turn_cnt != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.max_turn_cnt);
        }
        if self.is_auto_fight != false {
            my_size += 1 + 1;
        }
        if !self.csv_path.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.csv_path);
        }
        if self.is_battle_simulator_auto_fight != false {
            my_size += 1 + 1;
        }
        if self.FJKKJGGAFIA != false {
            my_size += 1 + 1;
        }
        if self.JFBIBFGIDME != 0 {
            my_size += ::protobuf::rt::uint32_size(7, self.JFBIBFGIDME);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.is_skip_verify != false {
            os.write_bool(1, self.is_skip_verify)?;
        }
        if self.max_turn_cnt != 0 {
            os.write_uint32(2, self.max_turn_cnt)?;
        }
        if self.is_auto_fight != false {
            os.write_bool(3, self.is_auto_fight)?;
        }
        if !self.csv_path.is_empty() {
            os.write_string(4, &self.csv_path)?;
        }
        if self.is_battle_simulator_auto_fight != false {
            os.write_bool(5, self.is_battle_simulator_auto_fight)?;
        }
        if self.FJKKJGGAFIA != false {
            os.write_bool(6, self.FJKKJGGAFIA)?;
        }
        if self.JFBIBFGIDME != 0 {
            os.write_uint32(7, self.JFBIBFGIDME)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GamecoreConfig {
        GamecoreConfig::new()
    }

    fn clear(&mut self) {
        self.is_skip_verify = false;
        self.max_turn_cnt = 0;
        self.is_auto_fight = false;
        self.csv_path.clear();
        self.is_battle_simulator_auto_fight = false;
        self.FJKKJGGAFIA = false;
        self.JFBIBFGIDME = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GamecoreConfig {
        static instance: GamecoreConfig = GamecoreConfig {
            is_skip_verify: false,
            max_turn_cnt: 0,
            is_auto_fight: false,
            csv_path: ::std::string::String::new(),
            is_battle_simulator_auto_fight: false,
            FJKKJGGAFIA: false,
            JFBIBFGIDME: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GamecoreConfig {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GamecoreConfig").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GamecoreConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GamecoreConfig {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x14GamecoreConfig.proto\"\x9f\x02\n\x0eGamecoreConfig\x12$\n\x0eis_sk\
    ip_verify\x18\x01\x20\x01(\x08R\x0cisSkipVerify\x12\x20\n\x0cmax_turn_cn\
    t\x18\x02\x20\x01(\rR\nmaxTurnCnt\x12\"\n\ris_auto_fight\x18\x03\x20\x01\
    (\x08R\x0bisAutoFight\x12\x19\n\x08csv_path\x18\x04\x20\x01(\tR\x07csvPa\
    th\x12B\n\x1eis_battle_simulator_auto_fight\x18\x05\x20\x01(\x08R\x1aisB\
    attleSimulatorAutoFight\x12\x20\n\x0bFJKKJGGAFIA\x18\x06\x20\x01(\x08R\
    \x0bFJKKJGGAFIA\x12\x20\n\x0bJFBIBFGIDME\x18\x07\x20\x01(\rR\x0bJFBIBFGI\
    DMEb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(GamecoreConfig::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
