// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `GetFriendRecommendLineupScRsp.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:GetFriendRecommendLineupScRsp)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetFriendRecommendLineupScRsp {
    // message fields
    // @@protoc_insertion_point(field:GetFriendRecommendLineupScRsp.key)
    pub key: u32,
    // @@protoc_insertion_point(field:GetFriendRecommendLineupScRsp.LKFHEGKMLKI)
    pub LKFHEGKMLKI: bool,
    // @@protoc_insertion_point(field:GetFriendRecommendLineupScRsp.retcode)
    pub retcode: u32,
    // @@protoc_insertion_point(field:GetFriendRecommendLineupScRsp.challenge_recommend_list)
    pub challenge_recommend_list: ::std::vec::Vec<super::KOCLBBLEILB::KOCLBBLEILB>,
    // @@protoc_insertion_point(field:GetFriendRecommendLineupScRsp.type)
    pub type_: ::protobuf::EnumOrUnknown<super::LDPGCFIGHFD::LDPGCFIGHFD>,
    // special fields
    // @@protoc_insertion_point(special_field:GetFriendRecommendLineupScRsp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetFriendRecommendLineupScRsp {
    fn default() -> &'a GetFriendRecommendLineupScRsp {
        <GetFriendRecommendLineupScRsp as ::protobuf::Message>::default_instance()
    }
}

impl GetFriendRecommendLineupScRsp {
    pub fn new() -> GetFriendRecommendLineupScRsp {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "key",
            |m: &GetFriendRecommendLineupScRsp| { &m.key },
            |m: &mut GetFriendRecommendLineupScRsp| { &mut m.key },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "LKFHEGKMLKI",
            |m: &GetFriendRecommendLineupScRsp| { &m.LKFHEGKMLKI },
            |m: &mut GetFriendRecommendLineupScRsp| { &mut m.LKFHEGKMLKI },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retcode",
            |m: &GetFriendRecommendLineupScRsp| { &m.retcode },
            |m: &mut GetFriendRecommendLineupScRsp| { &mut m.retcode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "challenge_recommend_list",
            |m: &GetFriendRecommendLineupScRsp| { &m.challenge_recommend_list },
            |m: &mut GetFriendRecommendLineupScRsp| { &mut m.challenge_recommend_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &GetFriendRecommendLineupScRsp| { &m.type_ },
            |m: &mut GetFriendRecommendLineupScRsp| { &mut m.type_ },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetFriendRecommendLineupScRsp>(
            "GetFriendRecommendLineupScRsp",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetFriendRecommendLineupScRsp {
    const NAME: &'static str = "GetFriendRecommendLineupScRsp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                80 => {
                    self.key = is.read_uint32()?;
                },
                24 => {
                    self.LKFHEGKMLKI = is.read_bool()?;
                },
                72 => {
                    self.retcode = is.read_uint32()?;
                },
                90 => {
                    self.challenge_recommend_list.push(is.read_message()?);
                },
                120 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.key != 0 {
            my_size += ::protobuf::rt::uint32_size(10, self.key);
        }
        if self.LKFHEGKMLKI != false {
            my_size += 1 + 1;
        }
        if self.retcode != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.retcode);
        }
        for value in &self.challenge_recommend_list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.type_ != ::protobuf::EnumOrUnknown::new(super::LDPGCFIGHFD::LDPGCFIGHFD::LDPGCFIGHFD_ALOCMFAKBKP) {
            my_size += ::protobuf::rt::int32_size(15, self.type_.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.key != 0 {
            os.write_uint32(10, self.key)?;
        }
        if self.LKFHEGKMLKI != false {
            os.write_bool(3, self.LKFHEGKMLKI)?;
        }
        if self.retcode != 0 {
            os.write_uint32(9, self.retcode)?;
        }
        for v in &self.challenge_recommend_list {
            ::protobuf::rt::write_message_field_with_cached_size(11, v, os)?;
        };
        if self.type_ != ::protobuf::EnumOrUnknown::new(super::LDPGCFIGHFD::LDPGCFIGHFD::LDPGCFIGHFD_ALOCMFAKBKP) {
            os.write_enum(15, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetFriendRecommendLineupScRsp {
        GetFriendRecommendLineupScRsp::new()
    }

    fn clear(&mut self) {
        self.key = 0;
        self.LKFHEGKMLKI = false;
        self.retcode = 0;
        self.challenge_recommend_list.clear();
        self.type_ = ::protobuf::EnumOrUnknown::new(super::LDPGCFIGHFD::LDPGCFIGHFD::LDPGCFIGHFD_ALOCMFAKBKP);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetFriendRecommendLineupScRsp {
        static instance: GetFriendRecommendLineupScRsp = GetFriendRecommendLineupScRsp {
            key: 0,
            LKFHEGKMLKI: false,
            retcode: 0,
            challenge_recommend_list: ::std::vec::Vec::new(),
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetFriendRecommendLineupScRsp {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetFriendRecommendLineupScRsp").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetFriendRecommendLineupScRsp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetFriendRecommendLineupScRsp {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n#GetFriendRecommendLineupScRsp.proto\x1a\x11KOCLBBLEILB.proto\x1a\x11L\
    DPGCFIGHFD.proto\"\xd7\x01\n\x1dGetFriendRecommendLineupScRsp\x12\x10\n\
    \x03key\x18\n\x20\x01(\rR\x03key\x12\x20\n\x0bLKFHEGKMLKI\x18\x03\x20\
    \x01(\x08R\x0bLKFHEGKMLKI\x12\x18\n\x07retcode\x18\t\x20\x01(\rR\x07retc\
    ode\x12F\n\x18challenge_recommend_list\x18\x0b\x20\x03(\x0b2\x0c.KOCLBBL\
    EILBR\x16challengeRecommendList\x12\x20\n\x04type\x18\x0f\x20\x01(\x0e2\
    \x0c.LDPGCFIGHFDR\x04typeb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::KOCLBBLEILB::file_descriptor().clone());
            deps.push(super::LDPGCFIGHFD::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(GetFriendRecommendLineupScRsp::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
