// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `GHMLCIMANAM.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:GHMLCIMANAM)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GHMLCIMANAM {
    // message fields
    // @@protoc_insertion_point(field:GHMLCIMANAM.GMHPBDEJNCI)
    pub GMHPBDEJNCI: u32,
    // @@protoc_insertion_point(field:GHMLCIMANAM.switch_list)
    pub switch_list: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:GHMLCIMANAM.CFKKNEHABHH)
    pub CFKKNEHABHH: ::protobuf::EnumOrUnknown<super::ACOKICDKFCI::ACOKICDKFCI>,
    // special fields
    // @@protoc_insertion_point(special_field:GHMLCIMANAM.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GHMLCIMANAM {
    fn default() -> &'a GHMLCIMANAM {
        <GHMLCIMANAM as ::protobuf::Message>::default_instance()
    }
}

impl GHMLCIMANAM {
    pub fn new() -> GHMLCIMANAM {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GMHPBDEJNCI",
            |m: &GHMLCIMANAM| { &m.GMHPBDEJNCI },
            |m: &mut GHMLCIMANAM| { &mut m.GMHPBDEJNCI },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "switch_list",
            |m: &GHMLCIMANAM| { &m.switch_list },
            |m: &mut GHMLCIMANAM| { &mut m.switch_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CFKKNEHABHH",
            |m: &GHMLCIMANAM| { &m.CFKKNEHABHH },
            |m: &mut GHMLCIMANAM| { &mut m.CFKKNEHABHH },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GHMLCIMANAM>(
            "GHMLCIMANAM",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GHMLCIMANAM {
    const NAME: &'static str = "GHMLCIMANAM";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.GMHPBDEJNCI = is.read_uint32()?;
                },
                18 => {
                    is.read_repeated_packed_uint32_into(&mut self.switch_list)?;
                },
                16 => {
                    self.switch_list.push(is.read_uint32()?);
                },
                40 => {
                    self.CFKKNEHABHH = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.GMHPBDEJNCI != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.GMHPBDEJNCI);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(2, &self.switch_list);
        if self.CFKKNEHABHH != ::protobuf::EnumOrUnknown::new(super::ACOKICDKFCI::ACOKICDKFCI::ACOKICDKFCI_LHLEHMPKDPB) {
            my_size += ::protobuf::rt::int32_size(5, self.CFKKNEHABHH.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.GMHPBDEJNCI != 0 {
            os.write_uint32(1, self.GMHPBDEJNCI)?;
        }
        os.write_repeated_packed_uint32(2, &self.switch_list)?;
        if self.CFKKNEHABHH != ::protobuf::EnumOrUnknown::new(super::ACOKICDKFCI::ACOKICDKFCI::ACOKICDKFCI_LHLEHMPKDPB) {
            os.write_enum(5, ::protobuf::EnumOrUnknown::value(&self.CFKKNEHABHH))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GHMLCIMANAM {
        GHMLCIMANAM::new()
    }

    fn clear(&mut self) {
        self.GMHPBDEJNCI = 0;
        self.switch_list.clear();
        self.CFKKNEHABHH = ::protobuf::EnumOrUnknown::new(super::ACOKICDKFCI::ACOKICDKFCI::ACOKICDKFCI_LHLEHMPKDPB);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GHMLCIMANAM {
        static instance: GHMLCIMANAM = GHMLCIMANAM {
            GMHPBDEJNCI: 0,
            switch_list: ::std::vec::Vec::new(),
            CFKKNEHABHH: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GHMLCIMANAM {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GHMLCIMANAM").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GHMLCIMANAM {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GHMLCIMANAM {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11GHMLCIMANAM.proto\x1a\x11ACOKICDKFCI.proto\"\x80\x01\n\x0bGHMLCIMA\
    NAM\x12\x20\n\x0bGMHPBDEJNCI\x18\x01\x20\x01(\rR\x0bGMHPBDEJNCI\x12\x1f\
    \n\x0bswitch_list\x18\x02\x20\x03(\rR\nswitchList\x12.\n\x0bCFKKNEHABHH\
    \x18\x05\x20\x01(\x0e2\x0c.ACOKICDKFCIR\x0bCFKKNEHABHHb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::ACOKICDKFCI::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(GHMLCIMANAM::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
