// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `GKGLFGNHNLB.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:GKGLFGNHNLB)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GKGLFGNHNLB {
    // message fields
    // @@protoc_insertion_point(field:GKGLFGNHNLB.KOHMMPMJJAJ)
    pub KOHMMPMJJAJ: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.NIAHELJEKHD)
    pub NIAHELJEKHD: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.JMECOKCCHKK)
    pub JMECOKCCHKK: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.IOKLIJHBLID)
    pub IOKLIJHBLID: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.JEOFEKKMPFL)
    pub JEOFEKKMPFL: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.AOBCEHCBFAB)
    pub AOBCEHCBFAB: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.KMMEKHBKCHH)
    pub KMMEKHBKCHH: ::protobuf::MessageField<super::ACHJGEEKCAH::ACHJGEEKCAH>,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.BHBECCEFAAD)
    pub BHBECCEFAAD: ::std::collections::HashMap<u32, super::JIOCHILHLGD::JIOCHILHLGD>,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.LNLBOAHHPED)
    pub LNLBOAHHPED: bool,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.EDOHNMGIANM)
    pub EDOHNMGIANM: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.BEFFJKIAEHF)
    pub BEFFJKIAEHF: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.PFADOMLNMCJ)
    pub PFADOMLNMCJ: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.chapter_id)
    pub chapter_id: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.section_id)
    pub section_id: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.FAINMEALDDB)
    pub FAINMEALDDB: ::std::vec::Vec<super::OEKKLGOPMOL::OEKKLGOPMOL>,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.BPLAMGNAJND)
    pub BPLAMGNAJND: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.CJBFBBANLML)
    pub CJBFBBANLML: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.MPNPONMLPDO)
    pub MPNPONMLPDO: ::std::vec::Vec<super::EOFJGFCLIEF::EOFJGFCLIEF>,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.GLHLIKAEPIN)
    pub GLHLIKAEPIN: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.KKMNLOFEPAM)
    pub KKMNLOFEPAM: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.MACGDMOEPMM)
    pub MACGDMOEPMM: u32,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.PODCOJPEGCL)
    pub PODCOJPEGCL: ::protobuf::MessageField<super::HEHHADKPDOC::HEHHADKPDOC>,
    // @@protoc_insertion_point(field:GKGLFGNHNLB.CNPNHJDPHJH)
    pub CNPNHJDPHJH: u32,
    // special fields
    // @@protoc_insertion_point(special_field:GKGLFGNHNLB.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GKGLFGNHNLB {
    fn default() -> &'a GKGLFGNHNLB {
        <GKGLFGNHNLB as ::protobuf::Message>::default_instance()
    }
}

impl GKGLFGNHNLB {
    pub fn new() -> GKGLFGNHNLB {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(23);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KOHMMPMJJAJ",
            |m: &GKGLFGNHNLB| { &m.KOHMMPMJJAJ },
            |m: &mut GKGLFGNHNLB| { &mut m.KOHMMPMJJAJ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "NIAHELJEKHD",
            |m: &GKGLFGNHNLB| { &m.NIAHELJEKHD },
            |m: &mut GKGLFGNHNLB| { &mut m.NIAHELJEKHD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JMECOKCCHKK",
            |m: &GKGLFGNHNLB| { &m.JMECOKCCHKK },
            |m: &mut GKGLFGNHNLB| { &mut m.JMECOKCCHKK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "IOKLIJHBLID",
            |m: &GKGLFGNHNLB| { &m.IOKLIJHBLID },
            |m: &mut GKGLFGNHNLB| { &mut m.IOKLIJHBLID },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JEOFEKKMPFL",
            |m: &GKGLFGNHNLB| { &m.JEOFEKKMPFL },
            |m: &mut GKGLFGNHNLB| { &mut m.JEOFEKKMPFL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AOBCEHCBFAB",
            |m: &GKGLFGNHNLB| { &m.AOBCEHCBFAB },
            |m: &mut GKGLFGNHNLB| { &mut m.AOBCEHCBFAB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ACHJGEEKCAH::ACHJGEEKCAH>(
            "KMMEKHBKCHH",
            |m: &GKGLFGNHNLB| { &m.KMMEKHBKCHH },
            |m: &mut GKGLFGNHNLB| { &mut m.KMMEKHBKCHH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "BHBECCEFAAD",
            |m: &GKGLFGNHNLB| { &m.BHBECCEFAAD },
            |m: &mut GKGLFGNHNLB| { &mut m.BHBECCEFAAD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "LNLBOAHHPED",
            |m: &GKGLFGNHNLB| { &m.LNLBOAHHPED },
            |m: &mut GKGLFGNHNLB| { &mut m.LNLBOAHHPED },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EDOHNMGIANM",
            |m: &GKGLFGNHNLB| { &m.EDOHNMGIANM },
            |m: &mut GKGLFGNHNLB| { &mut m.EDOHNMGIANM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "BEFFJKIAEHF",
            |m: &GKGLFGNHNLB| { &m.BEFFJKIAEHF },
            |m: &mut GKGLFGNHNLB| { &mut m.BEFFJKIAEHF },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "PFADOMLNMCJ",
            |m: &GKGLFGNHNLB| { &m.PFADOMLNMCJ },
            |m: &mut GKGLFGNHNLB| { &mut m.PFADOMLNMCJ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "chapter_id",
            |m: &GKGLFGNHNLB| { &m.chapter_id },
            |m: &mut GKGLFGNHNLB| { &mut m.chapter_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "section_id",
            |m: &GKGLFGNHNLB| { &m.section_id },
            |m: &mut GKGLFGNHNLB| { &mut m.section_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "FAINMEALDDB",
            |m: &GKGLFGNHNLB| { &m.FAINMEALDDB },
            |m: &mut GKGLFGNHNLB| { &mut m.FAINMEALDDB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "BPLAMGNAJND",
            |m: &GKGLFGNHNLB| { &m.BPLAMGNAJND },
            |m: &mut GKGLFGNHNLB| { &mut m.BPLAMGNAJND },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CJBFBBANLML",
            |m: &GKGLFGNHNLB| { &m.CJBFBBANLML },
            |m: &mut GKGLFGNHNLB| { &mut m.CJBFBBANLML },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "MPNPONMLPDO",
            |m: &GKGLFGNHNLB| { &m.MPNPONMLPDO },
            |m: &mut GKGLFGNHNLB| { &mut m.MPNPONMLPDO },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GLHLIKAEPIN",
            |m: &GKGLFGNHNLB| { &m.GLHLIKAEPIN },
            |m: &mut GKGLFGNHNLB| { &mut m.GLHLIKAEPIN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KKMNLOFEPAM",
            |m: &GKGLFGNHNLB| { &m.KKMNLOFEPAM },
            |m: &mut GKGLFGNHNLB| { &mut m.KKMNLOFEPAM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MACGDMOEPMM",
            |m: &GKGLFGNHNLB| { &m.MACGDMOEPMM },
            |m: &mut GKGLFGNHNLB| { &mut m.MACGDMOEPMM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::HEHHADKPDOC::HEHHADKPDOC>(
            "PODCOJPEGCL",
            |m: &GKGLFGNHNLB| { &m.PODCOJPEGCL },
            |m: &mut GKGLFGNHNLB| { &mut m.PODCOJPEGCL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CNPNHJDPHJH",
            |m: &GKGLFGNHNLB| { &m.CNPNHJDPHJH },
            |m: &mut GKGLFGNHNLB| { &mut m.CNPNHJDPHJH },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GKGLFGNHNLB>(
            "GKGLFGNHNLB",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GKGLFGNHNLB {
    const NAME: &'static str = "GKGLFGNHNLB";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.KOHMMPMJJAJ = is.read_uint32()?;
                },
                16 => {
                    self.NIAHELJEKHD = is.read_uint32()?;
                },
                24 => {
                    self.JMECOKCCHKK = is.read_uint32()?;
                },
                32 => {
                    self.IOKLIJHBLID = is.read_uint32()?;
                },
                40 => {
                    self.JEOFEKKMPFL = is.read_uint32()?;
                },
                48 => {
                    self.AOBCEHCBFAB = is.read_uint32()?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.KMMEKHBKCHH)?;
                },
                74 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            8 => key = is.read_uint32()?,
                            18 => value = is.read_message()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.BHBECCEFAAD.insert(key, value);
                },
                80 => {
                    self.LNLBOAHHPED = is.read_bool()?;
                },
                88 => {
                    self.EDOHNMGIANM = is.read_uint32()?;
                },
                96 => {
                    self.BEFFJKIAEHF = is.read_uint32()?;
                },
                104 => {
                    self.PFADOMLNMCJ = is.read_uint32()?;
                },
                112 => {
                    self.chapter_id = is.read_uint32()?;
                },
                120 => {
                    self.section_id = is.read_uint32()?;
                },
                1850 => {
                    self.FAINMEALDDB.push(is.read_message()?);
                },
                2544 => {
                    self.BPLAMGNAJND = is.read_uint32()?;
                },
                4080 => {
                    self.CJBFBBANLML = is.read_uint32()?;
                },
                5242 => {
                    self.MPNPONMLPDO.push(is.read_message()?);
                },
                10184 => {
                    self.GLHLIKAEPIN = is.read_uint32()?;
                },
                10904 => {
                    self.KKMNLOFEPAM = is.read_uint32()?;
                },
                11624 => {
                    self.MACGDMOEPMM = is.read_uint32()?;
                },
                11794 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.PODCOJPEGCL)?;
                },
                13624 => {
                    self.CNPNHJDPHJH = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.KOHMMPMJJAJ != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.KOHMMPMJJAJ);
        }
        if self.NIAHELJEKHD != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.NIAHELJEKHD);
        }
        if self.JMECOKCCHKK != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.JMECOKCCHKK);
        }
        if self.IOKLIJHBLID != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.IOKLIJHBLID);
        }
        if self.JEOFEKKMPFL != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.JEOFEKKMPFL);
        }
        if self.AOBCEHCBFAB != 0 {
            my_size += ::protobuf::rt::uint32_size(6, self.AOBCEHCBFAB);
        }
        if let Some(v) = self.KMMEKHBKCHH.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for (k, v) in &self.BHBECCEFAAD {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::uint32_size(1, *k);
            let len = v.compute_size();
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        if self.LNLBOAHHPED != false {
            my_size += 1 + 1;
        }
        if self.EDOHNMGIANM != 0 {
            my_size += ::protobuf::rt::uint32_size(11, self.EDOHNMGIANM);
        }
        if self.BEFFJKIAEHF != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.BEFFJKIAEHF);
        }
        if self.PFADOMLNMCJ != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.PFADOMLNMCJ);
        }
        if self.chapter_id != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.chapter_id);
        }
        if self.section_id != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.section_id);
        }
        for value in &self.FAINMEALDDB {
            let len = value.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.BPLAMGNAJND != 0 {
            my_size += ::protobuf::rt::uint32_size(318, self.BPLAMGNAJND);
        }
        if self.CJBFBBANLML != 0 {
            my_size += ::protobuf::rt::uint32_size(510, self.CJBFBBANLML);
        }
        for value in &self.MPNPONMLPDO {
            let len = value.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.GLHLIKAEPIN != 0 {
            my_size += ::protobuf::rt::uint32_size(1273, self.GLHLIKAEPIN);
        }
        if self.KKMNLOFEPAM != 0 {
            my_size += ::protobuf::rt::uint32_size(1363, self.KKMNLOFEPAM);
        }
        if self.MACGDMOEPMM != 0 {
            my_size += ::protobuf::rt::uint32_size(1453, self.MACGDMOEPMM);
        }
        if let Some(v) = self.PODCOJPEGCL.as_ref() {
            let len = v.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.CNPNHJDPHJH != 0 {
            my_size += ::protobuf::rt::uint32_size(1703, self.CNPNHJDPHJH);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.KOHMMPMJJAJ != 0 {
            os.write_uint32(1, self.KOHMMPMJJAJ)?;
        }
        if self.NIAHELJEKHD != 0 {
            os.write_uint32(2, self.NIAHELJEKHD)?;
        }
        if self.JMECOKCCHKK != 0 {
            os.write_uint32(3, self.JMECOKCCHKK)?;
        }
        if self.IOKLIJHBLID != 0 {
            os.write_uint32(4, self.IOKLIJHBLID)?;
        }
        if self.JEOFEKKMPFL != 0 {
            os.write_uint32(5, self.JEOFEKKMPFL)?;
        }
        if self.AOBCEHCBFAB != 0 {
            os.write_uint32(6, self.AOBCEHCBFAB)?;
        }
        if let Some(v) = self.KMMEKHBKCHH.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        for (k, v) in &self.BHBECCEFAAD {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::uint32_size(1, *k);
            let len = v.cached_size() as u64;
            entry_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            os.write_raw_varint32(74)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_uint32(1, *k)?;
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if self.LNLBOAHHPED != false {
            os.write_bool(10, self.LNLBOAHHPED)?;
        }
        if self.EDOHNMGIANM != 0 {
            os.write_uint32(11, self.EDOHNMGIANM)?;
        }
        if self.BEFFJKIAEHF != 0 {
            os.write_uint32(12, self.BEFFJKIAEHF)?;
        }
        if self.PFADOMLNMCJ != 0 {
            os.write_uint32(13, self.PFADOMLNMCJ)?;
        }
        if self.chapter_id != 0 {
            os.write_uint32(14, self.chapter_id)?;
        }
        if self.section_id != 0 {
            os.write_uint32(15, self.section_id)?;
        }
        for v in &self.FAINMEALDDB {
            ::protobuf::rt::write_message_field_with_cached_size(231, v, os)?;
        };
        if self.BPLAMGNAJND != 0 {
            os.write_uint32(318, self.BPLAMGNAJND)?;
        }
        if self.CJBFBBANLML != 0 {
            os.write_uint32(510, self.CJBFBBANLML)?;
        }
        for v in &self.MPNPONMLPDO {
            ::protobuf::rt::write_message_field_with_cached_size(655, v, os)?;
        };
        if self.GLHLIKAEPIN != 0 {
            os.write_uint32(1273, self.GLHLIKAEPIN)?;
        }
        if self.KKMNLOFEPAM != 0 {
            os.write_uint32(1363, self.KKMNLOFEPAM)?;
        }
        if self.MACGDMOEPMM != 0 {
            os.write_uint32(1453, self.MACGDMOEPMM)?;
        }
        if let Some(v) = self.PODCOJPEGCL.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1474, v, os)?;
        }
        if self.CNPNHJDPHJH != 0 {
            os.write_uint32(1703, self.CNPNHJDPHJH)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GKGLFGNHNLB {
        GKGLFGNHNLB::new()
    }

    fn clear(&mut self) {
        self.KOHMMPMJJAJ = 0;
        self.NIAHELJEKHD = 0;
        self.JMECOKCCHKK = 0;
        self.IOKLIJHBLID = 0;
        self.JEOFEKKMPFL = 0;
        self.AOBCEHCBFAB = 0;
        self.KMMEKHBKCHH.clear();
        self.BHBECCEFAAD.clear();
        self.LNLBOAHHPED = false;
        self.EDOHNMGIANM = 0;
        self.BEFFJKIAEHF = 0;
        self.PFADOMLNMCJ = 0;
        self.chapter_id = 0;
        self.section_id = 0;
        self.FAINMEALDDB.clear();
        self.BPLAMGNAJND = 0;
        self.CJBFBBANLML = 0;
        self.MPNPONMLPDO.clear();
        self.GLHLIKAEPIN = 0;
        self.KKMNLOFEPAM = 0;
        self.MACGDMOEPMM = 0;
        self.PODCOJPEGCL.clear();
        self.CNPNHJDPHJH = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GKGLFGNHNLB {
        static instance: ::protobuf::rt::Lazy<GKGLFGNHNLB> = ::protobuf::rt::Lazy::new();
        instance.get(GKGLFGNHNLB::new)
    }
}

impl ::protobuf::MessageFull for GKGLFGNHNLB {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GKGLFGNHNLB").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GKGLFGNHNLB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GKGLFGNHNLB {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11GKGLFGNHNLB.proto\x1a\x11ACHJGEEKCAH.proto\x1a\x11EOFJGFCLIEF.prot\
    o\x1a\x11HEHHADKPDOC.proto\x1a\x11JIOCHILHLGD.proto\x1a\x11OEKKLGOPMOL.p\
    roto\"\xc3\x07\n\x0bGKGLFGNHNLB\x12\x20\n\x0bKOHMMPMJJAJ\x18\x01\x20\x01\
    (\rR\x0bKOHMMPMJJAJ\x12\x20\n\x0bNIAHELJEKHD\x18\x02\x20\x01(\rR\x0bNIAH\
    ELJEKHD\x12\x20\n\x0bJMECOKCCHKK\x18\x03\x20\x01(\rR\x0bJMECOKCCHKK\x12\
    \x20\n\x0bIOKLIJHBLID\x18\x04\x20\x01(\rR\x0bIOKLIJHBLID\x12\x20\n\x0bJE\
    OFEKKMPFL\x18\x05\x20\x01(\rR\x0bJEOFEKKMPFL\x12\x20\n\x0bAOBCEHCBFAB\
    \x18\x06\x20\x01(\rR\x0bAOBCEHCBFAB\x12.\n\x0bKMMEKHBKCHH\x18\x08\x20\
    \x01(\x0b2\x0c.ACHJGEEKCAHR\x0bKMMEKHBKCHH\x12?\n\x0bBHBECCEFAAD\x18\t\
    \x20\x03(\x0b2\x1d.GKGLFGNHNLB.BHBECCEFAADEntryR\x0bBHBECCEFAAD\x12\x20\
    \n\x0bLNLBOAHHPED\x18\n\x20\x01(\x08R\x0bLNLBOAHHPED\x12\x20\n\x0bEDOHNM\
    GIANM\x18\x0b\x20\x01(\rR\x0bEDOHNMGIANM\x12\x20\n\x0bBEFFJKIAEHF\x18\
    \x0c\x20\x01(\rR\x0bBEFFJKIAEHF\x12\x20\n\x0bPFADOMLNMCJ\x18\r\x20\x01(\
    \rR\x0bPFADOMLNMCJ\x12\x1d\n\nchapter_id\x18\x0e\x20\x01(\rR\tchapterId\
    \x12\x1d\n\nsection_id\x18\x0f\x20\x01(\rR\tsectionId\x12/\n\x0bFAINMEAL\
    DDB\x18\xe7\x01\x20\x03(\x0b2\x0c.OEKKLGOPMOLR\x0bFAINMEALDDB\x12!\n\x0b\
    BPLAMGNAJND\x18\xbe\x02\x20\x01(\rR\x0bBPLAMGNAJND\x12!\n\x0bCJBFBBANLML\
    \x18\xfe\x03\x20\x01(\rR\x0bCJBFBBANLML\x12/\n\x0bMPNPONMLPDO\x18\x8f\
    \x05\x20\x03(\x0b2\x0c.EOFJGFCLIEFR\x0bMPNPONMLPDO\x12!\n\x0bGLHLIKAEPIN\
    \x18\xf9\t\x20\x01(\rR\x0bGLHLIKAEPIN\x12!\n\x0bKKMNLOFEPAM\x18\xd3\n\
    \x20\x01(\rR\x0bKKMNLOFEPAM\x12!\n\x0bMACGDMOEPMM\x18\xad\x0b\x20\x01(\r\
    R\x0bMACGDMOEPMM\x12/\n\x0bPODCOJPEGCL\x18\xc2\x0b\x20\x01(\x0b2\x0c.HEH\
    HADKPDOCR\x0bPODCOJPEGCL\x12!\n\x0bCNPNHJDPHJH\x18\xa7\r\x20\x01(\rR\x0b\
    CNPNHJDPHJH\x1aL\n\x10BHBECCEFAADEntry\x12\x10\n\x03key\x18\x01\x20\x01(\
    \rR\x03key\x12\"\n\x05value\x18\x02\x20\x01(\x0b2\x0c.JIOCHILHLGDR\x05va\
    lue:\x028\x01b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(5);
            deps.push(super::ACHJGEEKCAH::file_descriptor().clone());
            deps.push(super::EOFJGFCLIEF::file_descriptor().clone());
            deps.push(super::HEHHADKPDOC::file_descriptor().clone());
            deps.push(super::JIOCHILHLGD::file_descriptor().clone());
            deps.push(super::OEKKLGOPMOL::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(GKGLFGNHNLB::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
