// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `HGPDFOILHAK.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:HGPDFOILHAK)
pub enum HGPDFOILHAK {
    // @@protoc_insertion_point(enum_value:HGPDFOILHAK.HGPDFOILHAK_OHOCJGPEIGF)
    HGPDFOILHAK_OHOCJGPEIGF = 0,
    // @@protoc_insertion_point(enum_value:HGPDFOILHAK.HGPDFOILHAK_KLMGEICFJLA)
    HGPDFOILHAK_KLMGEICFJLA = 1,
    // @@protoc_insertion_point(enum_value:HGPDFOILHAK.HGPDFOILHAK_OJBGEEJONMA)
    HGPDFOILHAK_OJBGEEJONMA = 2,
    // @@protoc_insertion_point(enum_value:HGPDFOILHAK.HGPDFOILHAK_LFFJIHINGCK)
    HGPDFOILHAK_LFFJIHINGCK = 3,
    // @@protoc_insertion_point(enum_value:HGPDFOILHAK.HGPDFOILHAK_LFGOFADCFGH)
    HGPDFOILHAK_LFGOFADCFGH = 4,
    // @@protoc_insertion_point(enum_value:HGPDFOILHAK.HGPDFOILHAK_OLKBIEDJEPC)
    HGPDFOILHAK_OLKBIEDJEPC = 5,
}

impl ::protobuf::Enum for HGPDFOILHAK {
    const NAME: &'static str = "HGPDFOILHAK";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<HGPDFOILHAK> {
        match value {
            0 => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_OHOCJGPEIGF),
            1 => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_KLMGEICFJLA),
            2 => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_OJBGEEJONMA),
            3 => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_LFFJIHINGCK),
            4 => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_LFGOFADCFGH),
            5 => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_OLKBIEDJEPC),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<HGPDFOILHAK> {
        match str {
            "HGPDFOILHAK_OHOCJGPEIGF" => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_OHOCJGPEIGF),
            "HGPDFOILHAK_KLMGEICFJLA" => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_KLMGEICFJLA),
            "HGPDFOILHAK_OJBGEEJONMA" => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_OJBGEEJONMA),
            "HGPDFOILHAK_LFFJIHINGCK" => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_LFFJIHINGCK),
            "HGPDFOILHAK_LFGOFADCFGH" => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_LFGOFADCFGH),
            "HGPDFOILHAK_OLKBIEDJEPC" => ::std::option::Option::Some(HGPDFOILHAK::HGPDFOILHAK_OLKBIEDJEPC),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [HGPDFOILHAK] = &[
        HGPDFOILHAK::HGPDFOILHAK_OHOCJGPEIGF,
        HGPDFOILHAK::HGPDFOILHAK_KLMGEICFJLA,
        HGPDFOILHAK::HGPDFOILHAK_OJBGEEJONMA,
        HGPDFOILHAK::HGPDFOILHAK_LFFJIHINGCK,
        HGPDFOILHAK::HGPDFOILHAK_LFGOFADCFGH,
        HGPDFOILHAK::HGPDFOILHAK_OLKBIEDJEPC,
    ];
}

impl ::protobuf::EnumFull for HGPDFOILHAK {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("HGPDFOILHAK").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for HGPDFOILHAK {
    fn default() -> Self {
        HGPDFOILHAK::HGPDFOILHAK_OHOCJGPEIGF
    }
}

impl HGPDFOILHAK {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<HGPDFOILHAK>("HGPDFOILHAK")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11HGPDFOILHAK.proto*\xbb\x01\n\x0bHGPDFOILHAK\x12\x1b\n\x17HGPDFOILH\
    AK_OHOCJGPEIGF\x10\0\x12\x1b\n\x17HGPDFOILHAK_KLMGEICFJLA\x10\x01\x12\
    \x1b\n\x17HGPDFOILHAK_OJBGEEJONMA\x10\x02\x12\x1b\n\x17HGPDFOILHAK_LFFJI\
    HINGCK\x10\x03\x12\x1b\n\x17HGPDFOILHAK_LFGOFADCFGH\x10\x04\x12\x1b\n\
    \x17HGPDFOILHAK_OLKBIEDJEPC\x10\x05b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(HGPDFOILHAK::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
