// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `IDKBGCOJHHJ.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:IDKBGCOJHHJ)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct IDKBGCOJHHJ {
    // message fields
    // @@protoc_insertion_point(field:IDKBGCOJHHJ.COPGBEFIKGE)
    pub COPGBEFIKGE: u64,
    // @@protoc_insertion_point(field:IDKBGCOJHHJ.GCLCCOGIDOA)
    pub GCLCCOGIDOA: u32,
    // @@protoc_insertion_point(field:IDKBGCOJHHJ.GBAHHHPMLDK)
    pub GBAHHHPMLDK: u32,
    // @@protoc_insertion_point(field:IDKBGCOJHHJ.LCHNDBNKNIO)
    pub LCHNDBNKNIO: ::std::vec::Vec<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:IDKBGCOJHHJ.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a IDKBGCOJHHJ {
    fn default() -> &'a IDKBGCOJHHJ {
        <IDKBGCOJHHJ as ::protobuf::Message>::default_instance()
    }
}

impl IDKBGCOJHHJ {
    pub fn new() -> IDKBGCOJHHJ {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "COPGBEFIKGE",
            |m: &IDKBGCOJHHJ| { &m.COPGBEFIKGE },
            |m: &mut IDKBGCOJHHJ| { &mut m.COPGBEFIKGE },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GCLCCOGIDOA",
            |m: &IDKBGCOJHHJ| { &m.GCLCCOGIDOA },
            |m: &mut IDKBGCOJHHJ| { &mut m.GCLCCOGIDOA },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GBAHHHPMLDK",
            |m: &IDKBGCOJHHJ| { &m.GBAHHHPMLDK },
            |m: &mut IDKBGCOJHHJ| { &mut m.GBAHHHPMLDK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "LCHNDBNKNIO",
            |m: &IDKBGCOJHHJ| { &m.LCHNDBNKNIO },
            |m: &mut IDKBGCOJHHJ| { &mut m.LCHNDBNKNIO },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<IDKBGCOJHHJ>(
            "IDKBGCOJHHJ",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for IDKBGCOJHHJ {
    const NAME: &'static str = "IDKBGCOJHHJ";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.COPGBEFIKGE = is.read_uint64()?;
                },
                16 => {
                    self.GCLCCOGIDOA = is.read_uint32()?;
                },
                24 => {
                    self.GBAHHHPMLDK = is.read_uint32()?;
                },
                34 => {
                    is.read_repeated_packed_uint32_into(&mut self.LCHNDBNKNIO)?;
                },
                32 => {
                    self.LCHNDBNKNIO.push(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.COPGBEFIKGE != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.COPGBEFIKGE);
        }
        if self.GCLCCOGIDOA != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.GCLCCOGIDOA);
        }
        if self.GBAHHHPMLDK != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.GBAHHHPMLDK);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(4, &self.LCHNDBNKNIO);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.COPGBEFIKGE != 0 {
            os.write_uint64(1, self.COPGBEFIKGE)?;
        }
        if self.GCLCCOGIDOA != 0 {
            os.write_uint32(2, self.GCLCCOGIDOA)?;
        }
        if self.GBAHHHPMLDK != 0 {
            os.write_uint32(3, self.GBAHHHPMLDK)?;
        }
        os.write_repeated_packed_uint32(4, &self.LCHNDBNKNIO)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> IDKBGCOJHHJ {
        IDKBGCOJHHJ::new()
    }

    fn clear(&mut self) {
        self.COPGBEFIKGE = 0;
        self.GCLCCOGIDOA = 0;
        self.GBAHHHPMLDK = 0;
        self.LCHNDBNKNIO.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static IDKBGCOJHHJ {
        static instance: IDKBGCOJHHJ = IDKBGCOJHHJ {
            COPGBEFIKGE: 0,
            GCLCCOGIDOA: 0,
            GBAHHHPMLDK: 0,
            LCHNDBNKNIO: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for IDKBGCOJHHJ {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("IDKBGCOJHHJ").unwrap()).clone()
    }
}

impl ::std::fmt::Display for IDKBGCOJHHJ {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for IDKBGCOJHHJ {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11IDKBGCOJHHJ.proto\"\x95\x01\n\x0bIDKBGCOJHHJ\x12\x20\n\x0bCOPGBEFI\
    KGE\x18\x01\x20\x01(\x04R\x0bCOPGBEFIKGE\x12\x20\n\x0bGCLCCOGIDOA\x18\
    \x02\x20\x01(\rR\x0bGCLCCOGIDOA\x12\x20\n\x0bGBAHHHPMLDK\x18\x03\x20\x01\
    (\rR\x0bGBAHHHPMLDK\x12\x20\n\x0bLCHNDBNKNIO\x18\x04\x20\x03(\rR\x0bLCHN\
    DBNKNIOb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(IDKBGCOJHHJ::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
