// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `JFNBFKBLGOH.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:JFNBFKBLGOH)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct JFNBFKBLGOH {
    // message fields
    // @@protoc_insertion_point(field:JFNBFKBLGOH.KNMOIMCAFIE)
    pub KNMOIMCAFIE: u32,
    // @@protoc_insertion_point(field:JFNBFKBLGOH.AIGDIGKLNFG)
    pub AIGDIGKLNFG: bool,
    // @@protoc_insertion_point(field:JFNBFKBLGOH.MEIIKOALMHM)
    pub MEIIKOALMHM: u32,
    // @@protoc_insertion_point(field:JFNBFKBLGOH.cell_id)
    pub cell_id: u32,
    // @@protoc_insertion_point(field:JFNBFKBLGOH.AINKFAMGGIG)
    pub AINKFAMGGIG: bool,
    // @@protoc_insertion_point(field:JFNBFKBLGOH.MJDIHMPMGCH)
    pub MJDIHMPMGCH: u32,
    // special fields
    // @@protoc_insertion_point(special_field:JFNBFKBLGOH.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a JFNBFKBLGOH {
    fn default() -> &'a JFNBFKBLGOH {
        <JFNBFKBLGOH as ::protobuf::Message>::default_instance()
    }
}

impl JFNBFKBLGOH {
    pub fn new() -> JFNBFKBLGOH {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KNMOIMCAFIE",
            |m: &JFNBFKBLGOH| { &m.KNMOIMCAFIE },
            |m: &mut JFNBFKBLGOH| { &mut m.KNMOIMCAFIE },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AIGDIGKLNFG",
            |m: &JFNBFKBLGOH| { &m.AIGDIGKLNFG },
            |m: &mut JFNBFKBLGOH| { &mut m.AIGDIGKLNFG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MEIIKOALMHM",
            |m: &JFNBFKBLGOH| { &m.MEIIKOALMHM },
            |m: &mut JFNBFKBLGOH| { &mut m.MEIIKOALMHM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "cell_id",
            |m: &JFNBFKBLGOH| { &m.cell_id },
            |m: &mut JFNBFKBLGOH| { &mut m.cell_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AINKFAMGGIG",
            |m: &JFNBFKBLGOH| { &m.AINKFAMGGIG },
            |m: &mut JFNBFKBLGOH| { &mut m.AINKFAMGGIG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MJDIHMPMGCH",
            |m: &JFNBFKBLGOH| { &m.MJDIHMPMGCH },
            |m: &mut JFNBFKBLGOH| { &mut m.MJDIHMPMGCH },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<JFNBFKBLGOH>(
            "JFNBFKBLGOH",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for JFNBFKBLGOH {
    const NAME: &'static str = "JFNBFKBLGOH";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.KNMOIMCAFIE = is.read_uint32()?;
                },
                48 => {
                    self.AIGDIGKLNFG = is.read_bool()?;
                },
                64 => {
                    self.MEIIKOALMHM = is.read_uint32()?;
                },
                72 => {
                    self.cell_id = is.read_uint32()?;
                },
                96 => {
                    self.AINKFAMGGIG = is.read_bool()?;
                },
                120 => {
                    self.MJDIHMPMGCH = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.KNMOIMCAFIE != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.KNMOIMCAFIE);
        }
        if self.AIGDIGKLNFG != false {
            my_size += 1 + 1;
        }
        if self.MEIIKOALMHM != 0 {
            my_size += ::protobuf::rt::uint32_size(8, self.MEIIKOALMHM);
        }
        if self.cell_id != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.cell_id);
        }
        if self.AINKFAMGGIG != false {
            my_size += 1 + 1;
        }
        if self.MJDIHMPMGCH != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.MJDIHMPMGCH);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.KNMOIMCAFIE != 0 {
            os.write_uint32(1, self.KNMOIMCAFIE)?;
        }
        if self.AIGDIGKLNFG != false {
            os.write_bool(6, self.AIGDIGKLNFG)?;
        }
        if self.MEIIKOALMHM != 0 {
            os.write_uint32(8, self.MEIIKOALMHM)?;
        }
        if self.cell_id != 0 {
            os.write_uint32(9, self.cell_id)?;
        }
        if self.AINKFAMGGIG != false {
            os.write_bool(12, self.AINKFAMGGIG)?;
        }
        if self.MJDIHMPMGCH != 0 {
            os.write_uint32(15, self.MJDIHMPMGCH)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> JFNBFKBLGOH {
        JFNBFKBLGOH::new()
    }

    fn clear(&mut self) {
        self.KNMOIMCAFIE = 0;
        self.AIGDIGKLNFG = false;
        self.MEIIKOALMHM = 0;
        self.cell_id = 0;
        self.AINKFAMGGIG = false;
        self.MJDIHMPMGCH = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static JFNBFKBLGOH {
        static instance: JFNBFKBLGOH = JFNBFKBLGOH {
            KNMOIMCAFIE: 0,
            AIGDIGKLNFG: false,
            MEIIKOALMHM: 0,
            cell_id: 0,
            AINKFAMGGIG: false,
            MJDIHMPMGCH: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for JFNBFKBLGOH {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("JFNBFKBLGOH").unwrap()).clone()
    }
}

impl ::std::fmt::Display for JFNBFKBLGOH {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for JFNBFKBLGOH {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11JFNBFKBLGOH.proto\"\xd0\x01\n\x0bJFNBFKBLGOH\x12\x20\n\x0bKNMOIMCA\
    FIE\x18\x01\x20\x01(\rR\x0bKNMOIMCAFIE\x12\x20\n\x0bAIGDIGKLNFG\x18\x06\
    \x20\x01(\x08R\x0bAIGDIGKLNFG\x12\x20\n\x0bMEIIKOALMHM\x18\x08\x20\x01(\
    \rR\x0bMEIIKOALMHM\x12\x17\n\x07cell_id\x18\t\x20\x01(\rR\x06cellId\x12\
    \x20\n\x0bAINKFAMGGIG\x18\x0c\x20\x01(\x08R\x0bAINKFAMGGIG\x12\x20\n\x0b\
    MJDIHMPMGCH\x18\x0f\x20\x01(\rR\x0bMJDIHMPMGCHb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(JFNBFKBLGOH::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
