// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `JNFELCKIOCM.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:JNFELCKIOCM)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct JNFELCKIOCM {
    // message fields
    // @@protoc_insertion_point(field:JNFELCKIOCM.chess_rogue_buff_info)
    pub chess_rogue_buff_info: ::protobuf::MessageField<super::ChessRogueBuff::ChessRogueBuff>,
    // @@protoc_insertion_point(field:JNFELCKIOCM.GMPIIAEGGEK)
    pub GMPIIAEGGEK: u32,
    // @@protoc_insertion_point(field:JNFELCKIOCM.KJGIMHFKGBN)
    pub KJGIMHFKGBN: u32,
    // @@protoc_insertion_point(field:JNFELCKIOCM.FFKPEGNBHOD)
    pub FFKPEGNBHOD: u32,
    // @@protoc_insertion_point(field:JNFELCKIOCM.chess_rogue_miracle_info)
    pub chess_rogue_miracle_info: ::protobuf::MessageField<super::ChessRogueMiracle::ChessRogueMiracle>,
    // @@protoc_insertion_point(field:JNFELCKIOCM.map_id)
    pub map_id: u32,
    // @@protoc_insertion_point(field:JNFELCKIOCM.trial_avatar_id_list)
    pub trial_avatar_id_list: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:JNFELCKIOCM.base_avatar_id_list)
    pub base_avatar_id_list: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:JNFELCKIOCM.status)
    pub status: ::protobuf::EnumOrUnknown<super::RogueStatus::RogueStatus>,
    // special fields
    // @@protoc_insertion_point(special_field:JNFELCKIOCM.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a JNFELCKIOCM {
    fn default() -> &'a JNFELCKIOCM {
        <JNFELCKIOCM as ::protobuf::Message>::default_instance()
    }
}

impl JNFELCKIOCM {
    pub fn new() -> JNFELCKIOCM {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(9);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ChessRogueBuff::ChessRogueBuff>(
            "chess_rogue_buff_info",
            |m: &JNFELCKIOCM| { &m.chess_rogue_buff_info },
            |m: &mut JNFELCKIOCM| { &mut m.chess_rogue_buff_info },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GMPIIAEGGEK",
            |m: &JNFELCKIOCM| { &m.GMPIIAEGGEK },
            |m: &mut JNFELCKIOCM| { &mut m.GMPIIAEGGEK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KJGIMHFKGBN",
            |m: &JNFELCKIOCM| { &m.KJGIMHFKGBN },
            |m: &mut JNFELCKIOCM| { &mut m.KJGIMHFKGBN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "FFKPEGNBHOD",
            |m: &JNFELCKIOCM| { &m.FFKPEGNBHOD },
            |m: &mut JNFELCKIOCM| { &mut m.FFKPEGNBHOD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ChessRogueMiracle::ChessRogueMiracle>(
            "chess_rogue_miracle_info",
            |m: &JNFELCKIOCM| { &m.chess_rogue_miracle_info },
            |m: &mut JNFELCKIOCM| { &mut m.chess_rogue_miracle_info },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "map_id",
            |m: &JNFELCKIOCM| { &m.map_id },
            |m: &mut JNFELCKIOCM| { &mut m.map_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "trial_avatar_id_list",
            |m: &JNFELCKIOCM| { &m.trial_avatar_id_list },
            |m: &mut JNFELCKIOCM| { &mut m.trial_avatar_id_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "base_avatar_id_list",
            |m: &JNFELCKIOCM| { &m.base_avatar_id_list },
            |m: &mut JNFELCKIOCM| { &mut m.base_avatar_id_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "status",
            |m: &JNFELCKIOCM| { &m.status },
            |m: &mut JNFELCKIOCM| { &mut m.status },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<JNFELCKIOCM>(
            "JNFELCKIOCM",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for JNFELCKIOCM {
    const NAME: &'static str = "JNFELCKIOCM";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.chess_rogue_buff_info)?;
                },
                120 => {
                    self.GMPIIAEGGEK = is.read_uint32()?;
                },
                40 => {
                    self.KJGIMHFKGBN = is.read_uint32()?;
                },
                96 => {
                    self.FFKPEGNBHOD = is.read_uint32()?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.chess_rogue_miracle_info)?;
                },
                88 => {
                    self.map_id = is.read_uint32()?;
                },
                106 => {
                    is.read_repeated_packed_uint32_into(&mut self.trial_avatar_id_list)?;
                },
                104 => {
                    self.trial_avatar_id_list.push(is.read_uint32()?);
                },
                114 => {
                    is.read_repeated_packed_uint32_into(&mut self.base_avatar_id_list)?;
                },
                112 => {
                    self.base_avatar_id_list.push(is.read_uint32()?);
                },
                32 => {
                    self.status = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.chess_rogue_buff_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.GMPIIAEGGEK != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.GMPIIAEGGEK);
        }
        if self.KJGIMHFKGBN != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.KJGIMHFKGBN);
        }
        if self.FFKPEGNBHOD != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.FFKPEGNBHOD);
        }
        if let Some(v) = self.chess_rogue_miracle_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.map_id != 0 {
            my_size += ::protobuf::rt::uint32_size(11, self.map_id);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(13, &self.trial_avatar_id_list);
        my_size += ::protobuf::rt::vec_packed_uint32_size(14, &self.base_avatar_id_list);
        if self.status != ::protobuf::EnumOrUnknown::new(super::RogueStatus::RogueStatus::ROGUE_STATUS_NONE) {
            my_size += ::protobuf::rt::int32_size(4, self.status.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.chess_rogue_buff_info.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if self.GMPIIAEGGEK != 0 {
            os.write_uint32(15, self.GMPIIAEGGEK)?;
        }
        if self.KJGIMHFKGBN != 0 {
            os.write_uint32(5, self.KJGIMHFKGBN)?;
        }
        if self.FFKPEGNBHOD != 0 {
            os.write_uint32(12, self.FFKPEGNBHOD)?;
        }
        if let Some(v) = self.chess_rogue_miracle_info.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if self.map_id != 0 {
            os.write_uint32(11, self.map_id)?;
        }
        os.write_repeated_packed_uint32(13, &self.trial_avatar_id_list)?;
        os.write_repeated_packed_uint32(14, &self.base_avatar_id_list)?;
        if self.status != ::protobuf::EnumOrUnknown::new(super::RogueStatus::RogueStatus::ROGUE_STATUS_NONE) {
            os.write_enum(4, ::protobuf::EnumOrUnknown::value(&self.status))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> JNFELCKIOCM {
        JNFELCKIOCM::new()
    }

    fn clear(&mut self) {
        self.chess_rogue_buff_info.clear();
        self.GMPIIAEGGEK = 0;
        self.KJGIMHFKGBN = 0;
        self.FFKPEGNBHOD = 0;
        self.chess_rogue_miracle_info.clear();
        self.map_id = 0;
        self.trial_avatar_id_list.clear();
        self.base_avatar_id_list.clear();
        self.status = ::protobuf::EnumOrUnknown::new(super::RogueStatus::RogueStatus::ROGUE_STATUS_NONE);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static JNFELCKIOCM {
        static instance: JNFELCKIOCM = JNFELCKIOCM {
            chess_rogue_buff_info: ::protobuf::MessageField::none(),
            GMPIIAEGGEK: 0,
            KJGIMHFKGBN: 0,
            FFKPEGNBHOD: 0,
            chess_rogue_miracle_info: ::protobuf::MessageField::none(),
            map_id: 0,
            trial_avatar_id_list: ::std::vec::Vec::new(),
            base_avatar_id_list: ::std::vec::Vec::new(),
            status: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for JNFELCKIOCM {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("JNFELCKIOCM").unwrap()).clone()
    }
}

impl ::std::fmt::Display for JNFELCKIOCM {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for JNFELCKIOCM {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11JNFELCKIOCM.proto\x1a\x14ChessRogueBuff.proto\x1a\x17ChessRogueMir\
    acle.proto\x1a\x11RogueStatus.proto\"\xa1\x03\n\x0bJNFELCKIOCM\x12B\n\
    \x15chess_rogue_buff_info\x18\x03\x20\x01(\x0b2\x0f.ChessRogueBuffR\x12c\
    hessRogueBuffInfo\x12\x20\n\x0bGMPIIAEGGEK\x18\x0f\x20\x01(\rR\x0bGMPIIA\
    EGGEK\x12\x20\n\x0bKJGIMHFKGBN\x18\x05\x20\x01(\rR\x0bKJGIMHFKGBN\x12\
    \x20\n\x0bFFKPEGNBHOD\x18\x0c\x20\x01(\rR\x0bFFKPEGNBHOD\x12K\n\x18chess\
    _rogue_miracle_info\x18\x08\x20\x01(\x0b2\x12.ChessRogueMiracleR\x15ches\
    sRogueMiracleInfo\x12\x15\n\x06map_id\x18\x0b\x20\x01(\rR\x05mapId\x12/\
    \n\x14trial_avatar_id_list\x18\r\x20\x03(\rR\x11trialAvatarIdList\x12-\n\
    \x13base_avatar_id_list\x18\x0e\x20\x03(\rR\x10baseAvatarIdList\x12$\n\
    \x06status\x18\x04\x20\x01(\x0e2\x0c.RogueStatusR\x06statusb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::ChessRogueBuff::file_descriptor().clone());
            deps.push(super::ChessRogueMiracle::file_descriptor().clone());
            deps.push(super::RogueStatus::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(JNFELCKIOCM::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
