// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `LAAINCMEMJC.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:LAAINCMEMJC)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct LAAINCMEMJC {
    // message fields
    // @@protoc_insertion_point(field:LAAINCMEMJC.AGPFFOEKAJC)
    pub AGPFFOEKAJC: u32,
    // @@protoc_insertion_point(field:LAAINCMEMJC.status)
    pub status: ::protobuf::EnumOrUnknown<super::IAGHENCFOMC::IAGHENCFOMC>,
    // special fields
    // @@protoc_insertion_point(special_field:LAAINCMEMJC.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LAAINCMEMJC {
    fn default() -> &'a LAAINCMEMJC {
        <LAAINCMEMJC as ::protobuf::Message>::default_instance()
    }
}

impl LAAINCMEMJC {
    pub fn new() -> LAAINCMEMJC {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AGPFFOEKAJC",
            |m: &LAAINCMEMJC| { &m.AGPFFOEKAJC },
            |m: &mut LAAINCMEMJC| { &mut m.AGPFFOEKAJC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "status",
            |m: &LAAINCMEMJC| { &m.status },
            |m: &mut LAAINCMEMJC| { &mut m.status },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LAAINCMEMJC>(
            "LAAINCMEMJC",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LAAINCMEMJC {
    const NAME: &'static str = "LAAINCMEMJC";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.AGPFFOEKAJC = is.read_uint32()?;
                },
                56 => {
                    self.status = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.AGPFFOEKAJC != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.AGPFFOEKAJC);
        }
        if self.status != ::protobuf::EnumOrUnknown::new(super::IAGHENCFOMC::IAGHENCFOMC::IAGHENCFOMC_GKJBAODJMJG) {
            my_size += ::protobuf::rt::int32_size(7, self.status.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.AGPFFOEKAJC != 0 {
            os.write_uint32(1, self.AGPFFOEKAJC)?;
        }
        if self.status != ::protobuf::EnumOrUnknown::new(super::IAGHENCFOMC::IAGHENCFOMC::IAGHENCFOMC_GKJBAODJMJG) {
            os.write_enum(7, ::protobuf::EnumOrUnknown::value(&self.status))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LAAINCMEMJC {
        LAAINCMEMJC::new()
    }

    fn clear(&mut self) {
        self.AGPFFOEKAJC = 0;
        self.status = ::protobuf::EnumOrUnknown::new(super::IAGHENCFOMC::IAGHENCFOMC::IAGHENCFOMC_GKJBAODJMJG);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LAAINCMEMJC {
        static instance: LAAINCMEMJC = LAAINCMEMJC {
            AGPFFOEKAJC: 0,
            status: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LAAINCMEMJC {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LAAINCMEMJC").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LAAINCMEMJC {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LAAINCMEMJC {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11LAAINCMEMJC.proto\x1a\x11IAGHENCFOMC.proto\"U\n\x0bLAAINCMEMJC\x12\
    \x20\n\x0bAGPFFOEKAJC\x18\x01\x20\x01(\rR\x0bAGPFFOEKAJC\x12$\n\x06statu\
    s\x18\x07\x20\x01(\x0e2\x0c.IAGHENCFOMCR\x06statusb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::IAGHENCFOMC::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(LAAINCMEMJC::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
