// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `LeaveRogueScRsp.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:LeaveRogueScRsp)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct LeaveRogueScRsp {
    // message fields
    // @@protoc_insertion_point(field:LeaveRogueScRsp.scene)
    pub scene: ::protobuf::MessageField<super::SceneInfo::SceneInfo>,
    // @@protoc_insertion_point(field:LeaveRogueScRsp.KEILFHHNLIH)
    pub KEILFHHNLIH: ::protobuf::MessageField<super::RogueMapRotateInfo::RogueMapRotateInfo>,
    // @@protoc_insertion_point(field:LeaveRogueScRsp.lineup)
    pub lineup: ::protobuf::MessageField<super::LineupInfo::LineupInfo>,
    // @@protoc_insertion_point(field:LeaveRogueScRsp.rogue_game_info)
    pub rogue_game_info: ::protobuf::MessageField<super::ILNFEFOBNEG::ILNFEFOBNEG>,
    // @@protoc_insertion_point(field:LeaveRogueScRsp.retcode)
    pub retcode: u32,
    // special fields
    // @@protoc_insertion_point(special_field:LeaveRogueScRsp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LeaveRogueScRsp {
    fn default() -> &'a LeaveRogueScRsp {
        <LeaveRogueScRsp as ::protobuf::Message>::default_instance()
    }
}

impl LeaveRogueScRsp {
    pub fn new() -> LeaveRogueScRsp {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::SceneInfo::SceneInfo>(
            "scene",
            |m: &LeaveRogueScRsp| { &m.scene },
            |m: &mut LeaveRogueScRsp| { &mut m.scene },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::RogueMapRotateInfo::RogueMapRotateInfo>(
            "KEILFHHNLIH",
            |m: &LeaveRogueScRsp| { &m.KEILFHHNLIH },
            |m: &mut LeaveRogueScRsp| { &mut m.KEILFHHNLIH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::LineupInfo::LineupInfo>(
            "lineup",
            |m: &LeaveRogueScRsp| { &m.lineup },
            |m: &mut LeaveRogueScRsp| { &mut m.lineup },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ILNFEFOBNEG::ILNFEFOBNEG>(
            "rogue_game_info",
            |m: &LeaveRogueScRsp| { &m.rogue_game_info },
            |m: &mut LeaveRogueScRsp| { &mut m.rogue_game_info },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retcode",
            |m: &LeaveRogueScRsp| { &m.retcode },
            |m: &mut LeaveRogueScRsp| { &mut m.retcode },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LeaveRogueScRsp>(
            "LeaveRogueScRsp",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LeaveRogueScRsp {
    const NAME: &'static str = "LeaveRogueScRsp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.scene)?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.KEILFHHNLIH)?;
                },
                90 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.lineup)?;
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.rogue_game_info)?;
                },
                40 => {
                    self.retcode = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.scene.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.KEILFHHNLIH.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.lineup.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.rogue_game_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.retcode != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.retcode);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.scene.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.KEILFHHNLIH.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        if let Some(v) = self.lineup.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(11, v, os)?;
        }
        if let Some(v) = self.rogue_game_info.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        if self.retcode != 0 {
            os.write_uint32(5, self.retcode)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LeaveRogueScRsp {
        LeaveRogueScRsp::new()
    }

    fn clear(&mut self) {
        self.scene.clear();
        self.KEILFHHNLIH.clear();
        self.lineup.clear();
        self.rogue_game_info.clear();
        self.retcode = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LeaveRogueScRsp {
        static instance: LeaveRogueScRsp = LeaveRogueScRsp {
            scene: ::protobuf::MessageField::none(),
            KEILFHHNLIH: ::protobuf::MessageField::none(),
            lineup: ::protobuf::MessageField::none(),
            rogue_game_info: ::protobuf::MessageField::none(),
            retcode: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LeaveRogueScRsp {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LeaveRogueScRsp").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LeaveRogueScRsp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LeaveRogueScRsp {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x15LeaveRogueScRsp.proto\x1a\x11ILNFEFOBNEG.proto\x1a\x10LineupInfo.p\
    roto\x1a\x18RogueMapRotateInfo.proto\x1a\x0fSceneInfo.proto\"\xdf\x01\n\
    \x0fLeaveRogueScRsp\x12\x20\n\x05scene\x18\x04\x20\x01(\x0b2\n.SceneInfo\
    R\x05scene\x125\n\x0bKEILFHHNLIH\x18\x06\x20\x01(\x0b2\x13.RogueMapRotat\
    eInfoR\x0bKEILFHHNLIH\x12#\n\x06lineup\x18\x0b\x20\x01(\x0b2\x0b.LineupI\
    nfoR\x06lineup\x124\n\x0frogue_game_info\x18\n\x20\x01(\x0b2\x0c.ILNFEFO\
    BNEGR\rrogueGameInfo\x12\x18\n\x07retcode\x18\x05\x20\x01(\rR\x07retcode\
    b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(4);
            deps.push(super::ILNFEFOBNEG::file_descriptor().clone());
            deps.push(super::LineupInfo::file_descriptor().clone());
            deps.push(super::RogueMapRotateInfo::file_descriptor().clone());
            deps.push(super::SceneInfo::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(LeaveRogueScRsp::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
