// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `MDJLOJFMEMC.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:MDJLOJFMEMC)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MDJLOJFMEMC {
    // message fields
    // @@protoc_insertion_point(field:MDJLOJFMEMC.AIGEHHNHKPM)
    pub AIGEHHNHKPM: u32,
    // @@protoc_insertion_point(field:MDJLOJFMEMC.KIEKJEFFPHK)
    pub KIEKJEFFPHK: u32,
    // @@protoc_insertion_point(field:MDJLOJFMEMC.reward)
    pub reward: ::protobuf::MessageField<super::ItemList::ItemList>,
    // @@protoc_insertion_point(field:MDJLOJFMEMC.progress)
    pub progress: u32,
    // @@protoc_insertion_point(field:MDJLOJFMEMC.KFDAICILNMB)
    pub KFDAICILNMB: bool,
    // @@protoc_insertion_point(field:MDJLOJFMEMC.EEEHGHKOCJI)
    pub EEEHGHKOCJI: bool,
    // @@protoc_insertion_point(field:MDJLOJFMEMC.script_id)
    pub script_id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:MDJLOJFMEMC.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MDJLOJFMEMC {
    fn default() -> &'a MDJLOJFMEMC {
        <MDJLOJFMEMC as ::protobuf::Message>::default_instance()
    }
}

impl MDJLOJFMEMC {
    pub fn new() -> MDJLOJFMEMC {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AIGEHHNHKPM",
            |m: &MDJLOJFMEMC| { &m.AIGEHHNHKPM },
            |m: &mut MDJLOJFMEMC| { &mut m.AIGEHHNHKPM },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KIEKJEFFPHK",
            |m: &MDJLOJFMEMC| { &m.KIEKJEFFPHK },
            |m: &mut MDJLOJFMEMC| { &mut m.KIEKJEFFPHK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::ItemList::ItemList>(
            "reward",
            |m: &MDJLOJFMEMC| { &m.reward },
            |m: &mut MDJLOJFMEMC| { &mut m.reward },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "progress",
            |m: &MDJLOJFMEMC| { &m.progress },
            |m: &mut MDJLOJFMEMC| { &mut m.progress },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KFDAICILNMB",
            |m: &MDJLOJFMEMC| { &m.KFDAICILNMB },
            |m: &mut MDJLOJFMEMC| { &mut m.KFDAICILNMB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EEEHGHKOCJI",
            |m: &MDJLOJFMEMC| { &m.EEEHGHKOCJI },
            |m: &mut MDJLOJFMEMC| { &mut m.EEEHGHKOCJI },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "script_id",
            |m: &MDJLOJFMEMC| { &m.script_id },
            |m: &mut MDJLOJFMEMC| { &mut m.script_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MDJLOJFMEMC>(
            "MDJLOJFMEMC",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MDJLOJFMEMC {
    const NAME: &'static str = "MDJLOJFMEMC";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                88 => {
                    self.AIGEHHNHKPM = is.read_uint32()?;
                },
                8 => {
                    self.KIEKJEFFPHK = is.read_uint32()?;
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.reward)?;
                },
                40 => {
                    self.progress = is.read_uint32()?;
                },
                112 => {
                    self.KFDAICILNMB = is.read_bool()?;
                },
                72 => {
                    self.EEEHGHKOCJI = is.read_bool()?;
                },
                104 => {
                    self.script_id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.AIGEHHNHKPM != 0 {
            my_size += ::protobuf::rt::uint32_size(11, self.AIGEHHNHKPM);
        }
        if self.KIEKJEFFPHK != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.KIEKJEFFPHK);
        }
        if let Some(v) = self.reward.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.progress != 0 {
            my_size += ::protobuf::rt::uint32_size(5, self.progress);
        }
        if self.KFDAICILNMB != false {
            my_size += 1 + 1;
        }
        if self.EEEHGHKOCJI != false {
            my_size += 1 + 1;
        }
        if self.script_id != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.script_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.AIGEHHNHKPM != 0 {
            os.write_uint32(11, self.AIGEHHNHKPM)?;
        }
        if self.KIEKJEFFPHK != 0 {
            os.write_uint32(1, self.KIEKJEFFPHK)?;
        }
        if let Some(v) = self.reward.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        if self.progress != 0 {
            os.write_uint32(5, self.progress)?;
        }
        if self.KFDAICILNMB != false {
            os.write_bool(14, self.KFDAICILNMB)?;
        }
        if self.EEEHGHKOCJI != false {
            os.write_bool(9, self.EEEHGHKOCJI)?;
        }
        if self.script_id != 0 {
            os.write_uint32(13, self.script_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MDJLOJFMEMC {
        MDJLOJFMEMC::new()
    }

    fn clear(&mut self) {
        self.AIGEHHNHKPM = 0;
        self.KIEKJEFFPHK = 0;
        self.reward.clear();
        self.progress = 0;
        self.KFDAICILNMB = false;
        self.EEEHGHKOCJI = false;
        self.script_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MDJLOJFMEMC {
        static instance: MDJLOJFMEMC = MDJLOJFMEMC {
            AIGEHHNHKPM: 0,
            KIEKJEFFPHK: 0,
            reward: ::protobuf::MessageField::none(),
            progress: 0,
            KFDAICILNMB: false,
            EEEHGHKOCJI: false,
            script_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MDJLOJFMEMC {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MDJLOJFMEMC").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MDJLOJFMEMC {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MDJLOJFMEMC {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11MDJLOJFMEMC.proto\x1a\x0eItemList.proto\"\xf1\x01\n\x0bMDJLOJFMEMC\
    \x12\x20\n\x0bAIGEHHNHKPM\x18\x0b\x20\x01(\rR\x0bAIGEHHNHKPM\x12\x20\n\
    \x0bKIEKJEFFPHK\x18\x01\x20\x01(\rR\x0bKIEKJEFFPHK\x12!\n\x06reward\x18\
    \n\x20\x01(\x0b2\t.ItemListR\x06reward\x12\x1a\n\x08progress\x18\x05\x20\
    \x01(\rR\x08progress\x12\x20\n\x0bKFDAICILNMB\x18\x0e\x20\x01(\x08R\x0bK\
    FDAICILNMB\x12\x20\n\x0bEEEHGHKOCJI\x18\t\x20\x01(\x08R\x0bEEEHGHKOCJI\
    \x12\x1b\n\tscript_id\x18\r\x20\x01(\rR\x08scriptIdb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::ItemList::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(MDJLOJFMEMC::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
