// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `NMBIMHPBHOO.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:NMBIMHPBHOO)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NMBIMHPBHOO {
    // message fields
    // @@protoc_insertion_point(field:NMBIMHPBHOO.JBNNMEJGHII)
    pub JBNNMEJGHII: ::std::vec::Vec<super::GridFightSectionRecordInfo::GridFightSectionRecordInfo>,
    // @@protoc_insertion_point(field:NMBIMHPBHOO.grid_fight_damage_stt_info)
    pub grid_fight_damage_stt_info: ::protobuf::MessageField<super::GridFightDamageSttInfo::GridFightDamageSttInfo>,
    // special fields
    // @@protoc_insertion_point(special_field:NMBIMHPBHOO.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NMBIMHPBHOO {
    fn default() -> &'a NMBIMHPBHOO {
        <NMBIMHPBHOO as ::protobuf::Message>::default_instance()
    }
}

impl NMBIMHPBHOO {
    pub fn new() -> NMBIMHPBHOO {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "JBNNMEJGHII",
            |m: &NMBIMHPBHOO| { &m.JBNNMEJGHII },
            |m: &mut NMBIMHPBHOO| { &mut m.JBNNMEJGHII },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::GridFightDamageSttInfo::GridFightDamageSttInfo>(
            "grid_fight_damage_stt_info",
            |m: &NMBIMHPBHOO| { &m.grid_fight_damage_stt_info },
            |m: &mut NMBIMHPBHOO| { &mut m.grid_fight_damage_stt_info },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NMBIMHPBHOO>(
            "NMBIMHPBHOO",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NMBIMHPBHOO {
    const NAME: &'static str = "NMBIMHPBHOO";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                26 => {
                    self.JBNNMEJGHII.push(is.read_message()?);
                },
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.grid_fight_damage_stt_info)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.JBNNMEJGHII {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.grid_fight_damage_stt_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.JBNNMEJGHII {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        if let Some(v) = self.grid_fight_damage_stt_info.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NMBIMHPBHOO {
        NMBIMHPBHOO::new()
    }

    fn clear(&mut self) {
        self.JBNNMEJGHII.clear();
        self.grid_fight_damage_stt_info.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NMBIMHPBHOO {
        static instance: NMBIMHPBHOO = NMBIMHPBHOO {
            JBNNMEJGHII: ::std::vec::Vec::new(),
            grid_fight_damage_stt_info: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NMBIMHPBHOO {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NMBIMHPBHOO").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NMBIMHPBHOO {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NMBIMHPBHOO {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11NMBIMHPBHOO.proto\x1a\x1cGridFightDamageSttInfo.proto\x1a\x20GridF\
    ightSectionRecordInfo.proto\"\xa1\x01\n\x0bNMBIMHPBHOO\x12=\n\x0bJBNNMEJ\
    GHII\x18\x03\x20\x03(\x0b2\x1b.GridFightSectionRecordInfoR\x0bJBNNMEJGHI\
    I\x12S\n\x1agrid_fight_damage_stt_info\x18\x01\x20\x01(\x0b2\x17.GridFig\
    htDamageSttInfoR\x16gridFightDamageSttInfob\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::GridFightDamageSttInfo::file_descriptor().clone());
            deps.push(super::GridFightSectionRecordInfo::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(NMBIMHPBHOO::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
