// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `NMOPLIGAKGM.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:NMOPLIGAKGM)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NMOPLIGAKGM {
    // message fields
    // @@protoc_insertion_point(field:NMOPLIGAKGM.battle_wave_id)
    pub battle_wave_id: u32,
    // @@protoc_insertion_point(field:NMOPLIGAKGM.JNBIALMKFCL)
    pub JNBIALMKFCL: u32,
    // @@protoc_insertion_point(field:NMOPLIGAKGM.PMGEPADBKKK)
    pub PMGEPADBKKK: bool,
    // @@protoc_insertion_point(field:NMOPLIGAKGM.GMCCILGOMLI)
    pub GMCCILGOMLI: ::protobuf::EnumOrUnknown<super::EJLGEOKIJKH::EJLGEOKIJKH>,
    // @@protoc_insertion_point(field:NMOPLIGAKGM.KBFHFLODGIA)
    pub KBFHFLODGIA: u32,
    // @@protoc_insertion_point(field:NMOPLIGAKGM.CANEJABOMFI)
    pub CANEJABOMFI: u32,
    // special fields
    // @@protoc_insertion_point(special_field:NMOPLIGAKGM.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NMOPLIGAKGM {
    fn default() -> &'a NMOPLIGAKGM {
        <NMOPLIGAKGM as ::protobuf::Message>::default_instance()
    }
}

impl NMOPLIGAKGM {
    pub fn new() -> NMOPLIGAKGM {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "battle_wave_id",
            |m: &NMOPLIGAKGM| { &m.battle_wave_id },
            |m: &mut NMOPLIGAKGM| { &mut m.battle_wave_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "JNBIALMKFCL",
            |m: &NMOPLIGAKGM| { &m.JNBIALMKFCL },
            |m: &mut NMOPLIGAKGM| { &mut m.JNBIALMKFCL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "PMGEPADBKKK",
            |m: &NMOPLIGAKGM| { &m.PMGEPADBKKK },
            |m: &mut NMOPLIGAKGM| { &mut m.PMGEPADBKKK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GMCCILGOMLI",
            |m: &NMOPLIGAKGM| { &m.GMCCILGOMLI },
            |m: &mut NMOPLIGAKGM| { &mut m.GMCCILGOMLI },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "KBFHFLODGIA",
            |m: &NMOPLIGAKGM| { &m.KBFHFLODGIA },
            |m: &mut NMOPLIGAKGM| { &mut m.KBFHFLODGIA },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "CANEJABOMFI",
            |m: &NMOPLIGAKGM| { &m.CANEJABOMFI },
            |m: &mut NMOPLIGAKGM| { &mut m.CANEJABOMFI },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NMOPLIGAKGM>(
            "NMOPLIGAKGM",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NMOPLIGAKGM {
    const NAME: &'static str = "NMOPLIGAKGM";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                16 => {
                    self.battle_wave_id = is.read_uint32()?;
                },
                32 => {
                    self.JNBIALMKFCL = is.read_uint32()?;
                },
                40 => {
                    self.PMGEPADBKKK = is.read_bool()?;
                },
                80 => {
                    self.GMCCILGOMLI = is.read_enum_or_unknown()?;
                },
                96 => {
                    self.KBFHFLODGIA = is.read_uint32()?;
                },
                112 => {
                    self.CANEJABOMFI = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.battle_wave_id != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.battle_wave_id);
        }
        if self.JNBIALMKFCL != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.JNBIALMKFCL);
        }
        if self.PMGEPADBKKK != false {
            my_size += 1 + 1;
        }
        if self.GMCCILGOMLI != ::protobuf::EnumOrUnknown::new(super::EJLGEOKIJKH::EJLGEOKIJKH::EJLGEOKIJKH_FOFDFIOGIDL) {
            my_size += ::protobuf::rt::int32_size(10, self.GMCCILGOMLI.value());
        }
        if self.KBFHFLODGIA != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.KBFHFLODGIA);
        }
        if self.CANEJABOMFI != 0 {
            my_size += ::protobuf::rt::uint32_size(14, self.CANEJABOMFI);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.battle_wave_id != 0 {
            os.write_uint32(2, self.battle_wave_id)?;
        }
        if self.JNBIALMKFCL != 0 {
            os.write_uint32(4, self.JNBIALMKFCL)?;
        }
        if self.PMGEPADBKKK != false {
            os.write_bool(5, self.PMGEPADBKKK)?;
        }
        if self.GMCCILGOMLI != ::protobuf::EnumOrUnknown::new(super::EJLGEOKIJKH::EJLGEOKIJKH::EJLGEOKIJKH_FOFDFIOGIDL) {
            os.write_enum(10, ::protobuf::EnumOrUnknown::value(&self.GMCCILGOMLI))?;
        }
        if self.KBFHFLODGIA != 0 {
            os.write_uint32(12, self.KBFHFLODGIA)?;
        }
        if self.CANEJABOMFI != 0 {
            os.write_uint32(14, self.CANEJABOMFI)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NMOPLIGAKGM {
        NMOPLIGAKGM::new()
    }

    fn clear(&mut self) {
        self.battle_wave_id = 0;
        self.JNBIALMKFCL = 0;
        self.PMGEPADBKKK = false;
        self.GMCCILGOMLI = ::protobuf::EnumOrUnknown::new(super::EJLGEOKIJKH::EJLGEOKIJKH::EJLGEOKIJKH_FOFDFIOGIDL);
        self.KBFHFLODGIA = 0;
        self.CANEJABOMFI = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NMOPLIGAKGM {
        static instance: NMOPLIGAKGM = NMOPLIGAKGM {
            battle_wave_id: 0,
            JNBIALMKFCL: 0,
            PMGEPADBKKK: false,
            GMCCILGOMLI: ::protobuf::EnumOrUnknown::from_i32(0),
            KBFHFLODGIA: 0,
            CANEJABOMFI: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NMOPLIGAKGM {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NMOPLIGAKGM").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NMOPLIGAKGM {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NMOPLIGAKGM {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11NMOPLIGAKGM.proto\x1a\x11EJLGEOKIJKH.proto\"\xeb\x01\n\x0bNMOPLIGA\
    KGM\x12$\n\x0ebattle_wave_id\x18\x02\x20\x01(\rR\x0cbattleWaveId\x12\x20\
    \n\x0bJNBIALMKFCL\x18\x04\x20\x01(\rR\x0bJNBIALMKFCL\x12\x20\n\x0bPMGEPA\
    DBKKK\x18\x05\x20\x01(\x08R\x0bPMGEPADBKKK\x12.\n\x0bGMCCILGOMLI\x18\n\
    \x20\x01(\x0e2\x0c.EJLGEOKIJKHR\x0bGMCCILGOMLI\x12\x20\n\x0bKBFHFLODGIA\
    \x18\x0c\x20\x01(\rR\x0bKBFHFLODGIA\x12\x20\n\x0bCANEJABOMFI\x18\x0e\x20\
    \x01(\rR\x0bCANEJABOMFIb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::EJLGEOKIJKH::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(NMOPLIGAKGM::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
