// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `OEBPDLGBCBB.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:OEBPDLGBCBB)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct OEBPDLGBCBB {
    // message fields
    // @@protoc_insertion_point(field:OEBPDLGBCBB.reason)
    pub reason: ::protobuf::EnumOrUnknown<super::JGPPDJHFIEK::JGPPDJHFIEK>,
    // @@protoc_insertion_point(field:OEBPDLGBCBB.data)
    pub data: ::protobuf::MessageField<super::KFJFEBMMOAO::KFJFEBMMOAO>,
    // special fields
    // @@protoc_insertion_point(special_field:OEBPDLGBCBB.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a OEBPDLGBCBB {
    fn default() -> &'a OEBPDLGBCBB {
        <OEBPDLGBCBB as ::protobuf::Message>::default_instance()
    }
}

impl OEBPDLGBCBB {
    pub fn new() -> OEBPDLGBCBB {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "reason",
            |m: &OEBPDLGBCBB| { &m.reason },
            |m: &mut OEBPDLGBCBB| { &mut m.reason },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::KFJFEBMMOAO::KFJFEBMMOAO>(
            "data",
            |m: &OEBPDLGBCBB| { &m.data },
            |m: &mut OEBPDLGBCBB| { &mut m.data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<OEBPDLGBCBB>(
            "OEBPDLGBCBB",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for OEBPDLGBCBB {
    const NAME: &'static str = "OEBPDLGBCBB";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                96 => {
                    self.reason = is.read_enum_or_unknown()?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.data)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.reason != ::protobuf::EnumOrUnknown::new(super::JGPPDJHFIEK::JGPPDJHFIEK::JGPPDJHFIEK_IFBDPCDMBGM) {
            my_size += ::protobuf::rt::int32_size(12, self.reason.value());
        }
        if let Some(v) = self.data.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.reason != ::protobuf::EnumOrUnknown::new(super::JGPPDJHFIEK::JGPPDJHFIEK::JGPPDJHFIEK_IFBDPCDMBGM) {
            os.write_enum(12, ::protobuf::EnumOrUnknown::value(&self.reason))?;
        }
        if let Some(v) = self.data.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> OEBPDLGBCBB {
        OEBPDLGBCBB::new()
    }

    fn clear(&mut self) {
        self.reason = ::protobuf::EnumOrUnknown::new(super::JGPPDJHFIEK::JGPPDJHFIEK::JGPPDJHFIEK_IFBDPCDMBGM);
        self.data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static OEBPDLGBCBB {
        static instance: OEBPDLGBCBB = OEBPDLGBCBB {
            reason: ::protobuf::EnumOrUnknown::from_i32(0),
            data: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for OEBPDLGBCBB {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("OEBPDLGBCBB").unwrap()).clone()
    }
}

impl ::std::fmt::Display for OEBPDLGBCBB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OEBPDLGBCBB {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11OEBPDLGBCBB.proto\x1a\x11JGPPDJHFIEK.proto\x1a\x11KFJFEBMMOAO.prot\
    o\"U\n\x0bOEBPDLGBCBB\x12$\n\x06reason\x18\x0c\x20\x01(\x0e2\x0c.JGPPDJH\
    FIEKR\x06reason\x12\x20\n\x04data\x18\x03\x20\x01(\x0b2\x0c.KFJFEBMMOAOR\
    \x04datab\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::JGPPDJHFIEK::file_descriptor().clone());
            deps.push(super::KFJFEBMMOAO::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(OEBPDLGBCBB::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
