// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `OHKDPNBGPOA.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:OHKDPNBGPOA)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct OHKDPNBGPOA {
    // message fields
    // @@protoc_insertion_point(field:OHKDPNBGPOA.MAKOLELFLFH)
    pub MAKOLELFLFH: bool,
    // @@protoc_insertion_point(field:OHKDPNBGPOA.DCJECFMMIBC)
    pub DCJECFMMIBC: bool,
    // @@protoc_insertion_point(field:OHKDPNBGPOA.GNFDDPEMMFN)
    pub GNFDDPEMMFN: bool,
    // @@protoc_insertion_point(field:OHKDPNBGPOA.PFBHGAHAFMD)
    pub PFBHGAHAFMD: bool,
    // @@protoc_insertion_point(field:OHKDPNBGPOA.IOJEAOCOBBF)
    pub IOJEAOCOBBF: bool,
    // special fields
    // @@protoc_insertion_point(special_field:OHKDPNBGPOA.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a OHKDPNBGPOA {
    fn default() -> &'a OHKDPNBGPOA {
        <OHKDPNBGPOA as ::protobuf::Message>::default_instance()
    }
}

impl OHKDPNBGPOA {
    pub fn new() -> OHKDPNBGPOA {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MAKOLELFLFH",
            |m: &OHKDPNBGPOA| { &m.MAKOLELFLFH },
            |m: &mut OHKDPNBGPOA| { &mut m.MAKOLELFLFH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "DCJECFMMIBC",
            |m: &OHKDPNBGPOA| { &m.DCJECFMMIBC },
            |m: &mut OHKDPNBGPOA| { &mut m.DCJECFMMIBC },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "GNFDDPEMMFN",
            |m: &OHKDPNBGPOA| { &m.GNFDDPEMMFN },
            |m: &mut OHKDPNBGPOA| { &mut m.GNFDDPEMMFN },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "PFBHGAHAFMD",
            |m: &OHKDPNBGPOA| { &m.PFBHGAHAFMD },
            |m: &mut OHKDPNBGPOA| { &mut m.PFBHGAHAFMD },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "IOJEAOCOBBF",
            |m: &OHKDPNBGPOA| { &m.IOJEAOCOBBF },
            |m: &mut OHKDPNBGPOA| { &mut m.IOJEAOCOBBF },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<OHKDPNBGPOA>(
            "OHKDPNBGPOA",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for OHKDPNBGPOA {
    const NAME: &'static str = "OHKDPNBGPOA";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                16 => {
                    self.MAKOLELFLFH = is.read_bool()?;
                },
                24 => {
                    self.DCJECFMMIBC = is.read_bool()?;
                },
                40 => {
                    self.GNFDDPEMMFN = is.read_bool()?;
                },
                64 => {
                    self.PFBHGAHAFMD = is.read_bool()?;
                },
                88 => {
                    self.IOJEAOCOBBF = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.MAKOLELFLFH != false {
            my_size += 1 + 1;
        }
        if self.DCJECFMMIBC != false {
            my_size += 1 + 1;
        }
        if self.GNFDDPEMMFN != false {
            my_size += 1 + 1;
        }
        if self.PFBHGAHAFMD != false {
            my_size += 1 + 1;
        }
        if self.IOJEAOCOBBF != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.MAKOLELFLFH != false {
            os.write_bool(2, self.MAKOLELFLFH)?;
        }
        if self.DCJECFMMIBC != false {
            os.write_bool(3, self.DCJECFMMIBC)?;
        }
        if self.GNFDDPEMMFN != false {
            os.write_bool(5, self.GNFDDPEMMFN)?;
        }
        if self.PFBHGAHAFMD != false {
            os.write_bool(8, self.PFBHGAHAFMD)?;
        }
        if self.IOJEAOCOBBF != false {
            os.write_bool(11, self.IOJEAOCOBBF)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> OHKDPNBGPOA {
        OHKDPNBGPOA::new()
    }

    fn clear(&mut self) {
        self.MAKOLELFLFH = false;
        self.DCJECFMMIBC = false;
        self.GNFDDPEMMFN = false;
        self.PFBHGAHAFMD = false;
        self.IOJEAOCOBBF = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static OHKDPNBGPOA {
        static instance: OHKDPNBGPOA = OHKDPNBGPOA {
            MAKOLELFLFH: false,
            DCJECFMMIBC: false,
            GNFDDPEMMFN: false,
            PFBHGAHAFMD: false,
            IOJEAOCOBBF: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for OHKDPNBGPOA {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("OHKDPNBGPOA").unwrap()).clone()
    }
}

impl ::std::fmt::Display for OHKDPNBGPOA {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OHKDPNBGPOA {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11OHKDPNBGPOA.proto\"\xb7\x01\n\x0bOHKDPNBGPOA\x12\x20\n\x0bMAKOLELF\
    LFH\x18\x02\x20\x01(\x08R\x0bMAKOLELFLFH\x12\x20\n\x0bDCJECFMMIBC\x18\
    \x03\x20\x01(\x08R\x0bDCJECFMMIBC\x12\x20\n\x0bGNFDDPEMMFN\x18\x05\x20\
    \x01(\x08R\x0bGNFDDPEMMFN\x12\x20\n\x0bPFBHGAHAFMD\x18\x08\x20\x01(\x08R\
    \x0bPFBHGAHAFMD\x12\x20\n\x0bIOJEAOCOBBF\x18\x0b\x20\x01(\x08R\x0bIOJEAO\
    COBBFb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(OHKDPNBGPOA::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
