// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `OIPOKOPAMPH.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:OIPOKOPAMPH)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct OIPOKOPAMPH {
    // message fields
    // @@protoc_insertion_point(field:OIPOKOPAMPH.AKGJJEFCGKB)
    pub AKGJJEFCGKB: u32,
    // @@protoc_insertion_point(field:OIPOKOPAMPH.IBIFIHDAKGK)
    pub IBIFIHDAKGK: ::protobuf::EnumOrUnknown<super::EJPMKKAGKMK::EJPMKKAGKMK>,
    // @@protoc_insertion_point(field:OIPOKOPAMPH.PLIJBFNMFFK)
    pub PLIJBFNMFFK: ::std::vec::Vec<super::MHMEDHFGKIA::MHMEDHFGKIA>,
    // @@protoc_insertion_point(field:OIPOKOPAMPH.AOIHDDOCAHH)
    pub AOIHDDOCAHH: ::protobuf::EnumOrUnknown<super::OHGNAAIBDOJ::OHGNAAIBDOJ>,
    // @@protoc_insertion_point(field:OIPOKOPAMPH.EKFDOGIGNEJ)
    pub EKFDOGIGNEJ: u32,
    // special fields
    // @@protoc_insertion_point(special_field:OIPOKOPAMPH.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a OIPOKOPAMPH {
    fn default() -> &'a OIPOKOPAMPH {
        <OIPOKOPAMPH as ::protobuf::Message>::default_instance()
    }
}

impl OIPOKOPAMPH {
    pub fn new() -> OIPOKOPAMPH {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AKGJJEFCGKB",
            |m: &OIPOKOPAMPH| { &m.AKGJJEFCGKB },
            |m: &mut OIPOKOPAMPH| { &mut m.AKGJJEFCGKB },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "IBIFIHDAKGK",
            |m: &OIPOKOPAMPH| { &m.IBIFIHDAKGK },
            |m: &mut OIPOKOPAMPH| { &mut m.IBIFIHDAKGK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "PLIJBFNMFFK",
            |m: &OIPOKOPAMPH| { &m.PLIJBFNMFFK },
            |m: &mut OIPOKOPAMPH| { &mut m.PLIJBFNMFFK },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "AOIHDDOCAHH",
            |m: &OIPOKOPAMPH| { &m.AOIHDDOCAHH },
            |m: &mut OIPOKOPAMPH| { &mut m.AOIHDDOCAHH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EKFDOGIGNEJ",
            |m: &OIPOKOPAMPH| { &m.EKFDOGIGNEJ },
            |m: &mut OIPOKOPAMPH| { &mut m.EKFDOGIGNEJ },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<OIPOKOPAMPH>(
            "OIPOKOPAMPH",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for OIPOKOPAMPH {
    const NAME: &'static str = "OIPOKOPAMPH";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                32 => {
                    self.AKGJJEFCGKB = is.read_uint32()?;
                },
                112 => {
                    self.IBIFIHDAKGK = is.read_enum_or_unknown()?;
                },
                42 => {
                    self.PLIJBFNMFFK.push(is.read_message()?);
                },
                16 => {
                    self.AOIHDDOCAHH = is.read_enum_or_unknown()?;
                },
                96 => {
                    self.EKFDOGIGNEJ = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.AKGJJEFCGKB != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.AKGJJEFCGKB);
        }
        if self.IBIFIHDAKGK != ::protobuf::EnumOrUnknown::new(super::EJPMKKAGKMK::EJPMKKAGKMK::EJPMKKAGKMK_MBCGBENNELF) {
            my_size += ::protobuf::rt::int32_size(14, self.IBIFIHDAKGK.value());
        }
        for value in &self.PLIJBFNMFFK {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.AOIHDDOCAHH != ::protobuf::EnumOrUnknown::new(super::OHGNAAIBDOJ::OHGNAAIBDOJ::OHGNAAIBDOJ_MAPMCJKMLFP) {
            my_size += ::protobuf::rt::int32_size(2, self.AOIHDDOCAHH.value());
        }
        if self.EKFDOGIGNEJ != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.EKFDOGIGNEJ);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.AKGJJEFCGKB != 0 {
            os.write_uint32(4, self.AKGJJEFCGKB)?;
        }
        if self.IBIFIHDAKGK != ::protobuf::EnumOrUnknown::new(super::EJPMKKAGKMK::EJPMKKAGKMK::EJPMKKAGKMK_MBCGBENNELF) {
            os.write_enum(14, ::protobuf::EnumOrUnknown::value(&self.IBIFIHDAKGK))?;
        }
        for v in &self.PLIJBFNMFFK {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        };
        if self.AOIHDDOCAHH != ::protobuf::EnumOrUnknown::new(super::OHGNAAIBDOJ::OHGNAAIBDOJ::OHGNAAIBDOJ_MAPMCJKMLFP) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.AOIHDDOCAHH))?;
        }
        if self.EKFDOGIGNEJ != 0 {
            os.write_uint32(12, self.EKFDOGIGNEJ)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> OIPOKOPAMPH {
        OIPOKOPAMPH::new()
    }

    fn clear(&mut self) {
        self.AKGJJEFCGKB = 0;
        self.IBIFIHDAKGK = ::protobuf::EnumOrUnknown::new(super::EJPMKKAGKMK::EJPMKKAGKMK::EJPMKKAGKMK_MBCGBENNELF);
        self.PLIJBFNMFFK.clear();
        self.AOIHDDOCAHH = ::protobuf::EnumOrUnknown::new(super::OHGNAAIBDOJ::OHGNAAIBDOJ::OHGNAAIBDOJ_MAPMCJKMLFP);
        self.EKFDOGIGNEJ = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static OIPOKOPAMPH {
        static instance: OIPOKOPAMPH = OIPOKOPAMPH {
            AKGJJEFCGKB: 0,
            IBIFIHDAKGK: ::protobuf::EnumOrUnknown::from_i32(0),
            PLIJBFNMFFK: ::std::vec::Vec::new(),
            AOIHDDOCAHH: ::protobuf::EnumOrUnknown::from_i32(0),
            EKFDOGIGNEJ: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for OIPOKOPAMPH {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("OIPOKOPAMPH").unwrap()).clone()
    }
}

impl ::std::fmt::Display for OIPOKOPAMPH {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OIPOKOPAMPH {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11OIPOKOPAMPH.proto\x1a\x11EJPMKKAGKMK.proto\x1a\x11MHMEDHFGKIA.prot\
    o\x1a\x11OHGNAAIBDOJ.proto\"\xe1\x01\n\x0bOIPOKOPAMPH\x12\x20\n\x0bAKGJJ\
    EFCGKB\x18\x04\x20\x01(\rR\x0bAKGJJEFCGKB\x12.\n\x0bIBIFIHDAKGK\x18\x0e\
    \x20\x01(\x0e2\x0c.EJPMKKAGKMKR\x0bIBIFIHDAKGK\x12.\n\x0bPLIJBFNMFFK\x18\
    \x05\x20\x03(\x0b2\x0c.MHMEDHFGKIAR\x0bPLIJBFNMFFK\x12.\n\x0bAOIHDDOCAHH\
    \x18\x02\x20\x01(\x0e2\x0c.OHGNAAIBDOJR\x0bAOIHDDOCAHH\x12\x20\n\x0bEKFD\
    OGIGNEJ\x18\x0c\x20\x01(\rR\x0bEKFDOGIGNEJb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::EJPMKKAGKMK::file_descriptor().clone());
            deps.push(super::MHMEDHFGKIA::file_descriptor().clone());
            deps.push(super::OHGNAAIBDOJ::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(OIPOKOPAMPH::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
