// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `RaidTargetInfo.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:RaidTargetInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RaidTargetInfo {
    // message fields
    // @@protoc_insertion_point(field:RaidTargetInfo.cur_progress)
    pub cur_progress: u32,
    // @@protoc_insertion_point(field:RaidTargetInfo.MMPPGMOLPLG)
    pub MMPPGMOLPLG: u32,
    // @@protoc_insertion_point(field:RaidTargetInfo.EHEGEOMCPFG)
    pub EHEGEOMCPFG: ::protobuf::EnumOrUnknown<super::RaidTargetStatus::RaidTargetStatus>,
    // special fields
    // @@protoc_insertion_point(special_field:RaidTargetInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RaidTargetInfo {
    fn default() -> &'a RaidTargetInfo {
        <RaidTargetInfo as ::protobuf::Message>::default_instance()
    }
}

impl RaidTargetInfo {
    pub fn new() -> RaidTargetInfo {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "cur_progress",
            |m: &RaidTargetInfo| { &m.cur_progress },
            |m: &mut RaidTargetInfo| { &mut m.cur_progress },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MMPPGMOLPLG",
            |m: &RaidTargetInfo| { &m.MMPPGMOLPLG },
            |m: &mut RaidTargetInfo| { &mut m.MMPPGMOLPLG },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EHEGEOMCPFG",
            |m: &RaidTargetInfo| { &m.EHEGEOMCPFG },
            |m: &mut RaidTargetInfo| { &mut m.EHEGEOMCPFG },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RaidTargetInfo>(
            "RaidTargetInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RaidTargetInfo {
    const NAME: &'static str = "RaidTargetInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.cur_progress = is.read_uint32()?;
                },
                16 => {
                    self.MMPPGMOLPLG = is.read_uint32()?;
                },
                120 => {
                    self.EHEGEOMCPFG = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.cur_progress != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.cur_progress);
        }
        if self.MMPPGMOLPLG != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.MMPPGMOLPLG);
        }
        if self.EHEGEOMCPFG != ::protobuf::EnumOrUnknown::new(super::RaidTargetStatus::RaidTargetStatus::RAID_TARGET_STATUS_NONE) {
            my_size += ::protobuf::rt::int32_size(15, self.EHEGEOMCPFG.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.cur_progress != 0 {
            os.write_uint32(1, self.cur_progress)?;
        }
        if self.MMPPGMOLPLG != 0 {
            os.write_uint32(2, self.MMPPGMOLPLG)?;
        }
        if self.EHEGEOMCPFG != ::protobuf::EnumOrUnknown::new(super::RaidTargetStatus::RaidTargetStatus::RAID_TARGET_STATUS_NONE) {
            os.write_enum(15, ::protobuf::EnumOrUnknown::value(&self.EHEGEOMCPFG))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RaidTargetInfo {
        RaidTargetInfo::new()
    }

    fn clear(&mut self) {
        self.cur_progress = 0;
        self.MMPPGMOLPLG = 0;
        self.EHEGEOMCPFG = ::protobuf::EnumOrUnknown::new(super::RaidTargetStatus::RaidTargetStatus::RAID_TARGET_STATUS_NONE);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RaidTargetInfo {
        static instance: RaidTargetInfo = RaidTargetInfo {
            cur_progress: 0,
            MMPPGMOLPLG: 0,
            EHEGEOMCPFG: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RaidTargetInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RaidTargetInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RaidTargetInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RaidTargetInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x14RaidTargetInfo.proto\x1a\x16RaidTargetStatus.proto\"\x8a\x01\n\x0e\
    RaidTargetInfo\x12!\n\x0ccur_progress\x18\x01\x20\x01(\rR\x0bcurProgress\
    \x12\x20\n\x0bMMPPGMOLPLG\x18\x02\x20\x01(\rR\x0bMMPPGMOLPLG\x123\n\x0bE\
    HEGEOMCPFG\x18\x0f\x20\x01(\x0e2\x11.RaidTargetStatusR\x0bEHEGEOMCPFGb\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::RaidTargetStatus::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(RaidTargetInfo::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
