// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `RelicSmartWearPlan.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:RelicSmartWearPlan)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RelicSmartWearPlan {
    // message fields
    // @@protoc_insertion_point(field:RelicSmartWearPlan.inside_relic_list)
    pub inside_relic_list: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:RelicSmartWearPlan.avatar_id)
    pub avatar_id: u32,
    // @@protoc_insertion_point(field:RelicSmartWearPlan.outside_relic_list)
    pub outside_relic_list: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:RelicSmartWearPlan.unique_id)
    pub unique_id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:RelicSmartWearPlan.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RelicSmartWearPlan {
    fn default() -> &'a RelicSmartWearPlan {
        <RelicSmartWearPlan as ::protobuf::Message>::default_instance()
    }
}

impl RelicSmartWearPlan {
    pub fn new() -> RelicSmartWearPlan {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "inside_relic_list",
            |m: &RelicSmartWearPlan| { &m.inside_relic_list },
            |m: &mut RelicSmartWearPlan| { &mut m.inside_relic_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "avatar_id",
            |m: &RelicSmartWearPlan| { &m.avatar_id },
            |m: &mut RelicSmartWearPlan| { &mut m.avatar_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "outside_relic_list",
            |m: &RelicSmartWearPlan| { &m.outside_relic_list },
            |m: &mut RelicSmartWearPlan| { &mut m.outside_relic_list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "unique_id",
            |m: &RelicSmartWearPlan| { &m.unique_id },
            |m: &mut RelicSmartWearPlan| { &mut m.unique_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RelicSmartWearPlan>(
            "RelicSmartWearPlan",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RelicSmartWearPlan {
    const NAME: &'static str = "RelicSmartWearPlan";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                34 => {
                    is.read_repeated_packed_uint32_into(&mut self.inside_relic_list)?;
                },
                32 => {
                    self.inside_relic_list.push(is.read_uint32()?);
                },
                96 => {
                    self.avatar_id = is.read_uint32()?;
                },
                114 => {
                    is.read_repeated_packed_uint32_into(&mut self.outside_relic_list)?;
                },
                112 => {
                    self.outside_relic_list.push(is.read_uint32()?);
                },
                64 => {
                    self.unique_id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_uint32_size(4, &self.inside_relic_list);
        if self.avatar_id != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.avatar_id);
        }
        my_size += ::protobuf::rt::vec_packed_uint32_size(14, &self.outside_relic_list);
        if self.unique_id != 0 {
            my_size += ::protobuf::rt::uint32_size(8, self.unique_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_uint32(4, &self.inside_relic_list)?;
        if self.avatar_id != 0 {
            os.write_uint32(12, self.avatar_id)?;
        }
        os.write_repeated_packed_uint32(14, &self.outside_relic_list)?;
        if self.unique_id != 0 {
            os.write_uint32(8, self.unique_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RelicSmartWearPlan {
        RelicSmartWearPlan::new()
    }

    fn clear(&mut self) {
        self.inside_relic_list.clear();
        self.avatar_id = 0;
        self.outside_relic_list.clear();
        self.unique_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RelicSmartWearPlan {
        static instance: RelicSmartWearPlan = RelicSmartWearPlan {
            inside_relic_list: ::std::vec::Vec::new(),
            avatar_id: 0,
            outside_relic_list: ::std::vec::Vec::new(),
            unique_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RelicSmartWearPlan {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RelicSmartWearPlan").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RelicSmartWearPlan {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RelicSmartWearPlan {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18RelicSmartWearPlan.proto\"\xa8\x01\n\x12RelicSmartWearPlan\x12*\n\
    \x11inside_relic_list\x18\x04\x20\x03(\rR\x0finsideRelicList\x12\x1b\n\t\
    avatar_id\x18\x0c\x20\x01(\rR\x08avatarId\x12,\n\x12outside_relic_list\
    \x18\x0e\x20\x03(\rR\x10outsideRelicList\x12\x1b\n\tunique_id\x18\x08\
    \x20\x01(\rR\x08uniqueIdb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(RelicSmartWearPlan::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
