// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ReportPlayerCsReq.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:ReportPlayerCsReq)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ReportPlayerCsReq {
    // message fields
    // @@protoc_insertion_point(field:ReportPlayerCsReq.MIMAKHAABAH)
    pub MIMAKHAABAH: ::std::string::String,
    // @@protoc_insertion_point(field:ReportPlayerCsReq.EHBCLJFPOOE)
    pub EHBCLJFPOOE: u32,
    // @@protoc_insertion_point(field:ReportPlayerCsReq.uid)
    pub uid: u32,
    // special fields
    // @@protoc_insertion_point(special_field:ReportPlayerCsReq.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ReportPlayerCsReq {
    fn default() -> &'a ReportPlayerCsReq {
        <ReportPlayerCsReq as ::protobuf::Message>::default_instance()
    }
}

impl ReportPlayerCsReq {
    pub fn new() -> ReportPlayerCsReq {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "MIMAKHAABAH",
            |m: &ReportPlayerCsReq| { &m.MIMAKHAABAH },
            |m: &mut ReportPlayerCsReq| { &mut m.MIMAKHAABAH },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "EHBCLJFPOOE",
            |m: &ReportPlayerCsReq| { &m.EHBCLJFPOOE },
            |m: &mut ReportPlayerCsReq| { &mut m.EHBCLJFPOOE },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "uid",
            |m: &ReportPlayerCsReq| { &m.uid },
            |m: &mut ReportPlayerCsReq| { &mut m.uid },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ReportPlayerCsReq>(
            "ReportPlayerCsReq",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ReportPlayerCsReq {
    const NAME: &'static str = "ReportPlayerCsReq";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                106 => {
                    self.MIMAKHAABAH = is.read_string()?;
                },
                96 => {
                    self.EHBCLJFPOOE = is.read_uint32()?;
                },
                80 => {
                    self.uid = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.MIMAKHAABAH.is_empty() {
            my_size += ::protobuf::rt::string_size(13, &self.MIMAKHAABAH);
        }
        if self.EHBCLJFPOOE != 0 {
            my_size += ::protobuf::rt::uint32_size(12, self.EHBCLJFPOOE);
        }
        if self.uid != 0 {
            my_size += ::protobuf::rt::uint32_size(10, self.uid);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.MIMAKHAABAH.is_empty() {
            os.write_string(13, &self.MIMAKHAABAH)?;
        }
        if self.EHBCLJFPOOE != 0 {
            os.write_uint32(12, self.EHBCLJFPOOE)?;
        }
        if self.uid != 0 {
            os.write_uint32(10, self.uid)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ReportPlayerCsReq {
        ReportPlayerCsReq::new()
    }

    fn clear(&mut self) {
        self.MIMAKHAABAH.clear();
        self.EHBCLJFPOOE = 0;
        self.uid = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ReportPlayerCsReq {
        static instance: ReportPlayerCsReq = ReportPlayerCsReq {
            MIMAKHAABAH: ::std::string::String::new(),
            EHBCLJFPOOE: 0,
            uid: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ReportPlayerCsReq {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ReportPlayerCsReq").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ReportPlayerCsReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ReportPlayerCsReq {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x17ReportPlayerCsReq.proto\"i\n\x11ReportPlayerCsReq\x12\x20\n\x0bMIM\
    AKHAABAH\x18\r\x20\x01(\tR\x0bMIMAKHAABAH\x12\x20\n\x0bEHBCLJFPOOE\x18\
    \x0c\x20\x01(\rR\x0bEHBCLJFPOOE\x12\x10\n\x03uid\x18\n\x20\x01(\rR\x03ui\
    db\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ReportPlayerCsReq::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
