// This file is generated by rust-protobuf 3.7.1. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ReviveRogueAvatarCsReq1.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_1;

// @@protoc_insertion_point(message:ReviveRogueAvatarCsReq1)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ReviveRogueAvatarCsReq1 {
    // message fields
    // @@protoc_insertion_point(field:ReviveRogueAvatarCsReq1.NOEPBNMJFGL)
    pub NOEPBNMJFGL: ::std::vec::Vec<u32>,
    // @@protoc_insertion_point(field:ReviveRogueAvatarCsReq1.interacted_prop_entity_id)
    pub interacted_prop_entity_id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:ReviveRogueAvatarCsReq1.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ReviveRogueAvatarCsReq1 {
    fn default() -> &'a ReviveRogueAvatarCsReq1 {
        <ReviveRogueAvatarCsReq1 as ::protobuf::Message>::default_instance()
    }
}

impl ReviveRogueAvatarCsReq1 {
    pub fn new() -> ReviveRogueAvatarCsReq1 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "NOEPBNMJFGL",
            |m: &ReviveRogueAvatarCsReq1| { &m.NOEPBNMJFGL },
            |m: &mut ReviveRogueAvatarCsReq1| { &mut m.NOEPBNMJFGL },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "interacted_prop_entity_id",
            |m: &ReviveRogueAvatarCsReq1| { &m.interacted_prop_entity_id },
            |m: &mut ReviveRogueAvatarCsReq1| { &mut m.interacted_prop_entity_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ReviveRogueAvatarCsReq1>(
            "ReviveRogueAvatarCsReq1",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ReviveRogueAvatarCsReq1 {
    const NAME: &'static str = "ReviveRogueAvatarCsReq1";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                82 => {
                    is.read_repeated_packed_uint32_into(&mut self.NOEPBNMJFGL)?;
                },
                80 => {
                    self.NOEPBNMJFGL.push(is.read_uint32()?);
                },
                104 => {
                    self.interacted_prop_entity_id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_uint32_size(10, &self.NOEPBNMJFGL);
        if self.interacted_prop_entity_id != 0 {
            my_size += ::protobuf::rt::uint32_size(13, self.interacted_prop_entity_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_uint32(10, &self.NOEPBNMJFGL)?;
        if self.interacted_prop_entity_id != 0 {
            os.write_uint32(13, self.interacted_prop_entity_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ReviveRogueAvatarCsReq1 {
        ReviveRogueAvatarCsReq1::new()
    }

    fn clear(&mut self) {
        self.NOEPBNMJFGL.clear();
        self.interacted_prop_entity_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ReviveRogueAvatarCsReq1 {
        static instance: ReviveRogueAvatarCsReq1 = ReviveRogueAvatarCsReq1 {
            NOEPBNMJFGL: ::std::vec::Vec::new(),
            interacted_prop_entity_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ReviveRogueAvatarCsReq1 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ReviveRogueAvatarCsReq1").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ReviveRogueAvatarCsReq1 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ReviveRogueAvatarCsReq1 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1dReviveRogueAvatarCsReq1.proto\"v\n\x17ReviveRogueAvatarCsReq1\x12\
    \x20\n\x0bNOEPBNMJFGL\x18\n\x20\x03(\rR\x0bNOEPBNMJFGL\x129\n\x19interac\
    ted_prop_entity_id\x18\r\x20\x01(\rR\x16interactedPropEntityIdb\x06proto\
    3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ReviveRogueAvatarCsReq1::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
